ALTER TABLE jobs ADD COLUMN warning_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN skipped_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN failed_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE jobs ADD COLUMN partial INTEGER NOT NULL DEFAULT 0;
