use super::common::{EvidenceCategoryDef, EvidencePathPattern};

pub(super) const LINUX_ARTIFACTS_CATEGORY_DEF: EvidenceCategoryDef = EvidenceCategoryDef {
    category: "LinuxArtifacts",
    display_name: "Linux 痕迹",
    evidence_kind: "linux_artifact",
    parser: "linux.artifacts",
    artifact_families: &[
        "LinuxJournal",
        "LinuxWtmp",
        "LinuxBashCommand",
        "LinuxAptEvent",
        "LinuxCronJob",
        "LinuxSudoEvent",
        "LinuxSystemConfig",
        "LinuxWebSite",
        "LinuxWebAccessLog",
        "LinuxWebErrorLog",
        "LinuxWebFinding",
        "LinuxMysqlConfig",
        "LinuxMysqlLogEntry",
        "LinuxMysqlFinding",
    ],
    patterns: &[
        EvidencePathPattern::Suffix("/etc/os-release"),
        EvidencePathPattern::Suffix("/usr/lib/os-release"),
        EvidencePathPattern::Suffix("/etc/passwd"),
        EvidencePathPattern::Suffix("/etc/group"),
        EvidencePathPattern::Suffix("/etc/hostname"),
        EvidencePathPattern::Suffix("/etc/hosts"),
        EvidencePathPattern::Suffix("/etc/fstab"),
        EvidencePathPattern::Suffix("/etc/resolv.conf"),
        EvidencePathPattern::Suffix("/etc/machine-id"),
        EvidencePathPattern::Suffix("/etc/pve/storage.cfg"),
        EvidencePathPattern::ContainsAndSuffix("/etc/pve/qemu-server/", ".conf"),
        EvidencePathPattern::ContainsAndSuffix("/etc/pve/lxc/", ".conf"),
        EvidencePathPattern::Suffix("/etc/pve/corosync.conf"),
        EvidencePathPattern::Suffix("/etc/corosync/corosync.conf"),
        EvidencePathPattern::Suffix(".journal"),
        EvidencePathPattern::Suffix(".journal~"),
        EvidencePathPattern::Contains("/var/log/journal/"),
        EvidencePathPattern::Contains("/run/log/journal/"),
        EvidencePathPattern::Suffix("/var/log/wtmp"),
        EvidencePathPattern::Contains("/var/log/wtmp."),
        EvidencePathPattern::Suffix("/var/log/btmp"),
        EvidencePathPattern::Contains("/var/log/btmp."),
        EvidencePathPattern::Suffix("/var/log/lastlog"),
        EvidencePathPattern::Suffix("/var/log/faillog"),
        EvidencePathPattern::Suffix(".bash_history"),
        EvidencePathPattern::Suffix(".zsh_history"),
        EvidencePathPattern::Suffix(".fish_history"),
        EvidencePathPattern::Suffix(".python_history"),
        EvidencePathPattern::Contains("/.local/share/fish/fish_history"),
        EvidencePathPattern::Contains("/var/log/apt/history.log"),
        EvidencePathPattern::Contains("/var/log/apt/history.log."),
        EvidencePathPattern::Contains("/var/log/dpkg.log"),
        EvidencePathPattern::Contains("/var/log/dpkg.log."),
        EvidencePathPattern::Suffix("/var/log/yum.log"),
        EvidencePathPattern::Contains("/var/log/yum.log."),
        EvidencePathPattern::Suffix("/var/log/dnf.log"),
        EvidencePathPattern::Contains("/var/log/dnf.log."),
        EvidencePathPattern::Suffix("/var/log/dnf.rpm.log"),
        EvidencePathPattern::Contains("/var/log/dnf.rpm.log."),
        EvidencePathPattern::Suffix("/etc/crontab"),
        EvidencePathPattern::Contains("/etc/cron.d/"),
        EvidencePathPattern::Contains("/etc/cron.daily/"),
        EvidencePathPattern::Contains("/etc/cron.hourly/"),
        EvidencePathPattern::Contains("/etc/cron.monthly/"),
        EvidencePathPattern::Contains("/etc/cron.weekly/"),
        EvidencePathPattern::Contains("/var/spool/cron/crontabs/"),
        EvidencePathPattern::Contains("/var/spool/cron/"),
        EvidencePathPattern::Suffix("/var/log/auth.log"),
        EvidencePathPattern::Contains("/var/log/auth.log."),
        EvidencePathPattern::Suffix("/var/log/secure"),
        EvidencePathPattern::Contains("/var/log/secure."),
        EvidencePathPattern::Suffix("/var/log/audit/audit.log"),
        EvidencePathPattern::Contains("/var/log/audit/audit.log."),
        EvidencePathPattern::Suffix("/var/log/syslog"),
        EvidencePathPattern::Contains("/var/log/syslog."),
        EvidencePathPattern::Suffix("/var/log/messages"),
        EvidencePathPattern::Contains("/var/log/messages."),
        EvidencePathPattern::Suffix("/var/log/kern.log"),
        EvidencePathPattern::Contains("/var/log/kern.log."),
        EvidencePathPattern::Suffix("/var/log/cloud-init.log"),
        EvidencePathPattern::Contains("/var/log/cloud-init.log."),
        EvidencePathPattern::Suffix("/var/log/pveproxy/access.log"),
        EvidencePathPattern::Contains("/var/log/pveproxy/access.log."),
        EvidencePathPattern::Suffix("/var/log/pvedaemon.log"),
        EvidencePathPattern::Contains("/var/log/pvedaemon.log."),
        EvidencePathPattern::Contains("/var/log/pve/tasks/"),
        EvidencePathPattern::Contains("/.ssh/authorized_keys"),
        EvidencePathPattern::Contains("/.ssh/known_hosts"),
        EvidencePathPattern::Contains("/etc/ssh/"),
        EvidencePathPattern::Contains("/etc/systemd/system/"),
        EvidencePathPattern::Contains("/lib/systemd/system/"),
        EvidencePathPattern::Contains("/usr/lib/systemd/system/"),
        EvidencePathPattern::Contains("/etc/init.d/"),
        EvidencePathPattern::Suffix("/etc/rc.local"),
        EvidencePathPattern::Contains("/etc/profile.d/"),
        EvidencePathPattern::Suffix("/etc/sudoers"),
        EvidencePathPattern::Contains("/etc/sudoers.d/"),
        EvidencePathPattern::Suffix("/etc/nginx/nginx.conf"),
        EvidencePathPattern::ContainsAndSuffix("/etc/nginx/conf.d/", ".conf"),
        EvidencePathPattern::Contains("/etc/nginx/sites-enabled/"),
        EvidencePathPattern::Suffix("/etc/apache2/apache2.conf"),
        EvidencePathPattern::Contains("/etc/apache2/sites-enabled/"),
        EvidencePathPattern::Suffix("/etc/httpd/conf/httpd.conf"),
        EvidencePathPattern::ContainsAndSuffix("/etc/httpd/conf.d/", ".conf"),
        EvidencePathPattern::Suffix("/var/log/nginx/access.log"),
        EvidencePathPattern::Contains("/var/log/nginx/access.log."),
        EvidencePathPattern::Suffix("/var/log/nginx/error.log"),
        EvidencePathPattern::Contains("/var/log/nginx/error.log."),
        EvidencePathPattern::Suffix("/var/log/apache2/access.log"),
        EvidencePathPattern::Contains("/var/log/apache2/access.log."),
        EvidencePathPattern::Suffix("/var/log/apache2/error.log"),
        EvidencePathPattern::Contains("/var/log/apache2/error.log."),
        EvidencePathPattern::Suffix("/var/log/httpd/access_log"),
        EvidencePathPattern::Contains("/var/log/httpd/access_log."),
        EvidencePathPattern::Suffix("/var/log/httpd/error_log"),
        EvidencePathPattern::Contains("/var/log/httpd/error_log."),
        EvidencePathPattern::ContainsAndSuffix("/var/www/", ".php"),
        EvidencePathPattern::ContainsAndSuffix("/var/www/", ".phtml"),
        EvidencePathPattern::ContainsAndSuffix("/var/www/", ".jsp"),
        EvidencePathPattern::ContainsAndSuffix("/var/www/", ".jspx"),
        EvidencePathPattern::ContainsAndSuffix("/usr/share/nginx/html/", ".php"),
        EvidencePathPattern::ContainsAndSuffix("/usr/share/nginx/html/", ".phtml"),
        EvidencePathPattern::ContainsAndSuffix("/usr/share/nginx/html/", ".jsp"),
        EvidencePathPattern::ContainsAndSuffix("/usr/share/nginx/html/", ".jspx"),
        EvidencePathPattern::Suffix("/etc/my.cnf"),
        EvidencePathPattern::Suffix("/etc/mysql/my.cnf"),
        EvidencePathPattern::ContainsAndSuffix("/etc/mysql/mysql.conf.d/", ".cnf"),
        EvidencePathPattern::ContainsAndSuffix("/etc/mysql/mariadb.conf.d/", ".cnf"),
        EvidencePathPattern::ContainsAndSuffix("/etc/mysql/conf.d/", ".cnf"),
        EvidencePathPattern::ContainsAndSuffix("/etc/my.cnf.d/", ".cnf"),
        EvidencePathPattern::Suffix("/var/log/mysql/error.log"),
        EvidencePathPattern::Contains("/var/log/mysql/error.log."),
        EvidencePathPattern::Suffix("/var/log/mysql/mysql.log"),
        EvidencePathPattern::Contains("/var/log/mysql/mysql.log."),
        EvidencePathPattern::Suffix("/var/log/mysql/mysql-slow.log"),
        EvidencePathPattern::Contains("/var/log/mysql/mysql-slow.log."),
        EvidencePathPattern::Suffix("/var/log/mysql/slow.log"),
        EvidencePathPattern::Contains("/var/log/mysql/slow.log."),
        EvidencePathPattern::Suffix("/var/log/mariadb/mariadb.log"),
        EvidencePathPattern::Contains("/var/log/mariadb/mariadb.log."),
        EvidencePathPattern::Suffix("/var/log/mysqld.log"),
        EvidencePathPattern::Contains("/var/log/mysqld.log."),
    ],
    matcher: None,
};
