use super::common::{EvidenceCategoryDef, EvidencePathPattern};

pub(super) const LINUX_ARTIFACTS_CATEGORY_DEF: EvidenceCategoryDef = EvidenceCategoryDef {
    category: "LinuxArtifacts",
    display_name: "Linux 痕迹",
    evidence_kind: "linux_artifact",
    parser: "linux.artifacts",
    artifact_families: &[
        "LinuxJournal",
        "LinuxWtmp",
        "LinuxBashCommand",
        "LinuxAptEvent",
        "LinuxCronJob",
        "LinuxSudoEvent",
        "LinuxSystemConfig",
        "LinuxWebSite",
        "LinuxWebAccessLog",
        "LinuxWebErrorLog",
        "LinuxWebFinding",
        "LinuxMysqlConfig",
        "LinuxMysqlLogEntry",
        "LinuxMysqlFinding",
    ],
    patterns: &[
        EvidencePathPattern::Suffix("/etc/os-release"),
        EvidencePathPattern::Suffix("/usr/lib/os-release"),
        EvidencePathPattern::Suffix("/etc/passwd"),
        EvidencePathPattern::Suffix("/etc/shadow"),
        EvidencePathPattern::Suffix("/etc/gshadow"),
        EvidencePathPattern::Suffix("/etc/group"),
        EvidencePathPattern::Suffix("/etc/hostname"),
        EvidencePathPattern::Suffix("/etc/hosts"),
        EvidencePathPattern::Suffix("/etc/fstab"),
        EvidencePathPattern::Suffix("/etc/resolv.conf"),
        EvidencePathPattern::Suffix("/etc/machine-id"),
        EvidencePathPattern::Suffix("/etc/login.defs"),
        EvidencePathPattern::Suffix("/etc/anacrontab"),
        EvidencePathPattern::Suffix("/etc/pve/storage.cfg"),
        EvidencePathPattern::ContainsAndSuffix("/etc/pve/qemu-server/", ".conf"),
        EvidencePathPattern::ContainsAndSuffix("/etc/pve/lxc/", ".conf"),
        EvidencePathPattern::Suffix("/etc/pve/corosync.conf"),
        EvidencePathPattern::Suffix("/etc/corosync/corosync.conf"),
        EvidencePathPattern::Suffix(".journal"),
        EvidencePathPattern::Suffix(".journal~"),
        EvidencePathPattern::Contains("/var/log/journal/"),
        EvidencePathPattern::Contains("/run/log/journal/"),
        EvidencePathPattern::Suffix("/var/log/wtmp"),
        EvidencePathPattern::Contains("/var/log/wtmp."),
        EvidencePathPattern::Suffix("/var/log/btmp"),
        EvidencePathPattern::Contains("/var/log/btmp."),
        EvidencePathPattern::Suffix("/var/log/utmp"),
        EvidencePathPattern::Suffix("/run/utmp"),
        EvidencePathPattern::Suffix("/var/log/lastlog"),
        EvidencePathPattern::Suffix("/var/log/faillog"),
        EvidencePathPattern::Suffix(".bash_history"),
        EvidencePathPattern::Suffix(".zsh_history"),
        EvidencePathPattern::Suffix(".fish_history"),
        EvidencePathPattern::Suffix(".python_history"),
        EvidencePathPattern::Contains("/.local/share/fish/fish_history"),
        EvidencePathPattern::Contains("/var/log/apt/history.log"),
        EvidencePathPattern::Contains("/var/log/apt/history.log."),
        EvidencePathPattern::Contains("/var/log/dpkg.log"),
        EvidencePathPattern::Contains("/var/log/dpkg.log."),
        EvidencePathPattern::Suffix("/var/log/yum.log"),
        EvidencePathPattern::Contains("/var/log/yum.log."),
        EvidencePathPattern::Suffix("/var/log/dnf.log"),
        EvidencePathPattern::Contains("/var/log/dnf.log."),
        EvidencePathPattern::Suffix("/var/log/dnf.rpm.log"),
        EvidencePathPattern::Contains("/var/log/dnf.rpm.log."),
        EvidencePathPattern::Suffix("/etc/crontab"),
        EvidencePathPattern::Contains("/etc/cron.d/"),
        EvidencePathPattern::Contains("/etc/cron.daily/"),
        EvidencePathPattern::Contains("/etc/cron.hourly/"),
        EvidencePathPattern::Contains("/etc/cron.monthly/"),
        EvidencePathPattern::Contains("/etc/cron.weekly/"),
        EvidencePathPattern::Contains("/var/spool/cron/crontabs/"),
        EvidencePathPattern::Contains("/var/spool/cron/"),
        EvidencePathPattern::Suffix("/var/log/auth.log"),
        EvidencePathPattern::Contains("/var/log/auth.log."),
        EvidencePathPattern::Suffix("/var/log/secure"),
        EvidencePathPattern::Contains("/var/log/secure."),
        EvidencePathPattern::Suffix("/var/log/audit/audit.log"),
        EvidencePathPattern::Contains("/var/log/audit/audit.log."),
        EvidencePathPattern::Suffix("/var/log/syslog"),
        EvidencePathPattern::Contains("/var/log/syslog."),
        EvidencePathPattern::Suffix("/var/log/messages"),
        EvidencePathPattern::Contains("/var/log/messages."),
        EvidencePathPattern::Suffix("/var/log/kern.log"),
        EvidencePathPattern::Contains("/var/log/kern.log."),
        EvidencePathPattern::Suffix("/var/log/cloud-init.log"),
        EvidencePathPattern::Contains("/var/log/cloud-init.log."),
        EvidencePathPattern::Suffix("/var/log/cron"),
        EvidencePathPattern::Contains("/var/log/cron."),
        EvidencePathPattern::Suffix("/var/log/daemon.log"),
        EvidencePathPattern::Contains("/var/log/daemon.log."),
        EvidencePathPattern::Suffix("/var/log/mail.log"),
        EvidencePathPattern::Contains("/var/log/mail.log."),
        EvidencePathPattern::Suffix("/var/log/maillog"),
        EvidencePathPattern::Contains("/var/log/maillog."),
        EvidencePathPattern::Suffix("/var/log/ufw.log"),
        EvidencePathPattern::Contains("/var/log/ufw.log."),
        EvidencePathPattern::Suffix("/var/log/fail2ban.log"),
        EvidencePathPattern::Contains("/var/log/fail2ban.log."),
        EvidencePathPattern::Suffix("/var/log/pveproxy/access.log"),
        EvidencePathPattern::Contains("/var/log/pveproxy/access.log."),
        EvidencePathPattern::Suffix("/var/log/pvedaemon.log"),
        EvidencePathPattern::Contains("/var/log/pvedaemon.log."),
        EvidencePathPattern::Contains("/var/log/pve/tasks/"),
        EvidencePathPattern::Contains("/.ssh/authorized_keys"),
        EvidencePathPattern::Contains("/.ssh/known_hosts"),
        EvidencePathPattern::Contains("/etc/ssh/"),
        EvidencePathPattern::Contains("/etc/systemd/system/"),
        EvidencePathPattern::Contains("/lib/systemd/system/"),
        EvidencePathPattern::Contains("/usr/lib/systemd/system/"),
        EvidencePathPattern::Contains("/etc/init.d/"),
        EvidencePathPattern::Suffix("/etc/rc.local"),
        EvidencePathPattern::Contains("/etc/profile.d/"),
        EvidencePathPattern::Suffix("/etc/sudoers"),
        EvidencePathPattern::Contains("/etc/sudoers.d/"),
        EvidencePathPattern::Suffix("/etc/nginx/nginx.conf"),
        EvidencePathPattern::ContainsAndSuffix("/etc/nginx/conf.d/", ".conf"),
        EvidencePathPattern::Contains("/etc/nginx/sites-enabled/"),
        EvidencePathPattern::Suffix("/etc/apache2/apache2.conf"),
        EvidencePathPattern::Contains("/etc/apache2/sites-enabled/"),
        EvidencePathPattern::Suffix("/etc/httpd/conf/httpd.conf"),
        EvidencePathPattern::ContainsAndSuffix("/etc/httpd/conf.d/", ".conf"),
        EvidencePathPattern::ContainsAndSuffix("/var/log/nginx/", ".log"),
        EvidencePathPattern::ContainsBoth("/var/log/nginx/", ".log."),
        EvidencePathPattern::ContainsAndSuffix("/var/log/apache2/", ".log"),
        EvidencePathPattern::ContainsBoth("/var/log/apache2/", ".log."),
        EvidencePathPattern::ContainsAndSuffix("/var/log/httpd/", ".log"),
        EvidencePathPattern::ContainsBoth("/var/log/httpd/", ".log."),
        // BaoTa (宝塔) panel layout: vhost site configs, panel-managed server
        // main configs, and the centralized /www/wwwlogs web log directory.
        EvidencePathPattern::ContainsAndSuffix("/www/server/panel/vhost/nginx/", ".conf"),
        EvidencePathPattern::ContainsAndSuffix("/www/server/panel/vhost/apache/", ".conf"),
        EvidencePathPattern::ContainsAndSuffix("/www/server/nginx/conf/", ".conf"),
        EvidencePathPattern::ContainsAndSuffix("/www/server/apache/conf/", ".conf"),
        EvidencePathPattern::ContainsAndSuffix("/www/wwwlogs/", ".log"),
        EvidencePathPattern::ContainsBoth("/www/wwwlogs/", ".log."),
        EvidencePathPattern::ContainsAndSuffix("/var/www/", ".php"),
        EvidencePathPattern::ContainsAndSuffix("/var/www/", ".phtml"),
        EvidencePathPattern::ContainsAndSuffix("/var/www/", ".jsp"),
        EvidencePathPattern::ContainsAndSuffix("/var/www/", ".jspx"),
        EvidencePathPattern::ContainsAndSuffix("/usr/share/nginx/html/", ".php"),
        EvidencePathPattern::ContainsAndSuffix("/usr/share/nginx/html/", ".phtml"),
        EvidencePathPattern::ContainsAndSuffix("/usr/share/nginx/html/", ".jsp"),
        EvidencePathPattern::ContainsAndSuffix("/usr/share/nginx/html/", ".jspx"),
        EvidencePathPattern::Suffix("/etc/my.cnf"),
        EvidencePathPattern::Suffix("/etc/mysql/my.cnf"),
        EvidencePathPattern::ContainsAndSuffix("/etc/mysql/mysql.conf.d/", ".cnf"),
        EvidencePathPattern::ContainsAndSuffix("/etc/mysql/mariadb.conf.d/", ".cnf"),
        EvidencePathPattern::ContainsAndSuffix("/etc/mysql/conf.d/", ".cnf"),
        EvidencePathPattern::ContainsAndSuffix("/etc/my.cnf.d/", ".cnf"),
        EvidencePathPattern::Suffix("/var/log/mysql/error.log"),
        EvidencePathPattern::Contains("/var/log/mysql/error.log."),
        EvidencePathPattern::Suffix("/var/log/mysql/mysql.log"),
        EvidencePathPattern::Contains("/var/log/mysql/mysql.log."),
        EvidencePathPattern::Suffix("/var/log/mysql/mysql-slow.log"),
        EvidencePathPattern::Contains("/var/log/mysql/mysql-slow.log."),
        EvidencePathPattern::Suffix("/var/log/mysql/slow.log"),
        EvidencePathPattern::Contains("/var/log/mysql/slow.log."),
        EvidencePathPattern::Suffix("/var/log/mariadb/mariadb.log"),
        EvidencePathPattern::Contains("/var/log/mariadb/mariadb.log."),
        EvidencePathPattern::Suffix("/var/log/mysqld.log"),
        EvidencePathPattern::Contains("/var/log/mysqld.log."),
    ],
    matcher: None,
};

#[cfg(test)]
#[path = "../../../tests/unit/analysis_service/candidates/linux.rs"]
mod tests;
