[package]
name = "artifacts-macos"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
thiserror.workspace = true
anyhow.workspace = true
domain.workspace = true
artifacts-core.workspace = true
tracing.workspace = true
rusqlite = { version = "0.31", features = ["bundled"] }
tempfile = "3"
