import {
  AnalysisExtractionRun,
  ArtifactRow,
  AnalysisFileClassification,
  AnalysisSystemInfo,
  BrowserHistorySummary,
  CaseMetrics,
  CaseSummary,
  CorrelationSnapshot,
  DataSourceSummary,
  EmailExtractionSummary,
  EvidenceClassificationSummary,
  FileEntryRow,
  GraphEdge,
  GraphNode,
  GraphQuery,
  GraphQueryResult,
  GraphSnapshot,
  JobSnapshot,
  RecentCase,
  RecentObject,
  RegistryStructuredSummary,
  ReportHistoryItem,
  ReportTemplate,
  RegistryExtractionSummary,
  SearchHit,
  TimelineEventDto,
  TraceItem,
  V2GovernanceSnapshot,
  V3GovernanceSnapshot,
  WarningItem,
} from '@/types/models';

export const currentCase: CaseSummary = {
  id: 'case-2026-fx-091',
  name: 'WannaCry 爆发溯源',
  number: '2026-FX-091',
  examiner: 'Qin Ao',
  createdAt: '2026-05-14T08:30:00Z',
  updatedAt: '2026-05-16T11:20:00Z',
};

export const caseMetrics: CaseMetrics = {
  dataSourceCount: 4,
  indexedFileCount: 1492033,
  timelineEventCount: 8401922,
  artifactCount: 45102,
};

export const recentObjects: RecentObject[] = [
  {
    id: 'obj-1',
    title: 'tasksche.exe',
    detail: '[MOCK] 鍖归厤 YARA 瑙勫垯: WannaCry_Payload锛堟紨绀烘牱鏈級',
    time: '2026-05-16T09:20:00Z',
    kind: 'file',
  },
  {
    id: 'obj-2',
    title: 'HKLM\\SOFTWARE\\WanaCrypt0r',
    detail: '[MOCK] 娉ㄥ唽琛ㄩ」宸插垱寤猴紙婕旂ず鐥曡抗锛?',
    time: '2026-05-16T08:20:00Z',
    kind: 'registry',
  },
];

export const recentCases: RecentCase[] = [
  {
    caseRoot: 'D:/Cases/WannaCry',
    name: 'WannaCry 爆发溯源',
    openedAt: '2026-05-16T11:20:00Z',
  },
  {
    caseRoot: 'D:/Cases/RDP-Lateral',
    name: 'RDP 妯悜绉诲姩鎺掓煡',
    openedAt: '2026-05-15T17:40:00Z',
  },
];

export const dataSources: DataSourceSummary[] = [
  {
    id: 'ds-001',
    name: 'FINCH-1.E01 [MOCK]',
    kind: 'e01',
    sourcePath: 'E:/evidence/mock/FINCH-1.E01',
    importedAt: '2026-05-16T10:30:00Z',
    fileCount: 12844,
    sourceHash: 'mock-finche01-sha256-demo-value',
    hashStatus: 'hashed',
    canonicalPath: 'E:/evidence/mock/FINCH-1.E01',
    evidenceSize: 274877906944,
    readerKind: 'e01',
    provenanceStatus: 'Recorded',
    warnings: ['MOCK DATA: forensic-looking evidence source for UI preview only.'],
    partitions: [
      {
        index: 1,
        name: 'EFI system partition',
        kindLabel: 'FAT',
        status: 'supported',
        offset: 1048576,
        length: 104857600,
        filesystem: 'FAT',
        typeGuid: 'C12A7328-F81F-11D2-BA4B-00A0C93EC93B',
      },
      {
        index: 2,
        name: 'Microsoft reserved partition',
        kindLabel: 'Microsoft reserved',
        status: 'unsupported',
        offset: 105906176,
        length: 16777216,
        typeGuid: 'E3C9E316-0B5C-4DB8-817D-F92DF00215AE',
      },
      {
        index: 3,
        name: 'Basic data partition',
        kindLabel: 'NTFS',
        status: 'supported',
        offset: 122683392,
        length: 136575975424,
        filesystem: 'NTFS',
        typeGuid: 'EBD0A0A2-B9E5-4433-87C0-68B6B72699C7',
      },
      {
        index: 5,
        name: 'Basic data partition',
        kindLabel: 'BitLocker',
        status: 'locked',
        offset: 137436856320,
        length: 137438953472,
        filesystem: 'BitLocker',
        typeGuid: 'EBD0A0A2-B9E5-4433-87C0-68B6B72699C7',
        unlockHint: 'BitLocker 鍒嗗尯闇€瑕佸厛瑙ｉ攣鍚庢墠鑳芥祻瑙堟枃浠跺唴瀹广€?',
      },
    ],
  },
  {
    id: 'ds-002',
    name: 'System32 Snapshot [MOCK]',
    kind: 'logical_directory',
    sourcePath: 'E:/mounted/mock/System32',
    importedAt: '2026-05-16T12:05:00Z',
    fileCount: 2801,
    sourceHash: undefined,
    hashStatus: 'unavailable',
    canonicalPath: 'E:/mounted/mock/System32',
    readerKind: 'logical_directory',
    provenanceStatus: 'Recorded',
    warnings: ['MOCK DATA: logical directory snapshot path is illustrative only.'],
    partitions: [],
  },
];

export const analysisSystemInfo: AnalysisSystemInfo = {
  computerName: 'BETA-LAB',
  osVersion: 'Windows Evidence Edition 24H2',
  buildNumber: '26000',
  registeredOwner: 'DFIR Team',
  productId: '00330-80000',
  timezone: 'China Standard Time',
  networkAdapters: [],
  bootHistory: [
    {
      timestamp: '2026-06-01T08:15:00Z',
      bootType: 'eventLogStarted',
      source: 'Windows/System32/winevt/Logs/System.evtx',
      eventId: 6005,
      recordId: 42,
      note: 'EventLog 6005 candidate; indicates the Event Log service started, not a direct boot assertion.',
      provenance: {
        dataSourceId: 'ds-001',
        artifactPath: 'Windows/System32/winevt/Logs/System.evtx',
        parser: 'evtx.boot_shutdown',
        parsedAt: '2026-06-01T10:00:00Z',
        status: 'parsed',
        warnings: [],
      },
    },
  ],
  status: 'parsed',
  warnings: [
    '寮€鍏虫満鍘嗗彶鏉ヨ嚜 EVTX EventLog/User32 candidate events锛屼笉绛夊悓浜庣洿鎺ョ郴缁熷惎鍔ㄦ柇瑷€銆?',
  ],
  provenance: [
    {
      dataSourceId: 'ds-001',
      artifactPath: 'Windows/System32/config/SYSTEM',
      parser: 'registry.system',
      parsedAt: '2026-06-01T10:00:00Z',
      status: 'parsed',
      warnings: [],
    },
    {
      dataSourceId: 'ds-001',
      artifactPath: 'Windows/System32/config/SOFTWARE',
      parser: 'registry.software',
      parsedAt: '2026-06-01T10:00:00Z',
      status: 'parsed',
      warnings: [],
    },
    {
      dataSourceId: 'ds-001',
      artifactPath: 'Windows/System32/winevt/Logs/System.evtx',
      parser: 'evtx.boot_shutdown',
      parsedAt: '2026-06-01T10:00:00Z',
      status: 'parsed',
      warnings: [],
    },
  ],
  fieldProvenance: [
    {
      field: 'computerName',
      valueName: 'ComputerName',
      keyPath: 'ControlSet001\\Control\\ComputerName\\ComputerName',
      hivePath: 'Windows/System32/config/SYSTEM',
      parser: 'registry.system',
    },
    {
      field: 'osVersion',
      valueName: 'ProductName',
      keyPath: 'Microsoft\\Windows NT\\CurrentVersion',
      hivePath: 'Windows/System32/config/SOFTWARE',
      parser: 'registry.software',
    },
    {
      field: 'timezone',
      valueName: 'TimeZoneKeyName',
      keyPath: 'ControlSet001\\Control\\TimeZoneInformation',
      hivePath: 'Windows/System32/config/SYSTEM',
      parser: 'registry.system',
    },
  ],
};

export const analysisClassifications: AnalysisFileClassification[] = [
  {
    category: 'Executables',
    fileCount: 1,
    totalSize: 10200000,
    status: 'parsed',
    warnings: [],
    files: [
      {
        fileId: 'file-ntoskrnl',
        path: 'C:/Windows/System32/ntoskrnl.exe',
        name: 'ntoskrnl.exe',
        size: 10200000,
        fileType: 'PE',
        magicDescription: 'Windows Executable',
        provenance: {
          dataSourceId: 'ds-001',
          artifactPath: 'C:/Windows/System32/ntoskrnl.exe',
          parser: 'metadata.extension_path',
          parsedAt: '2026-06-01T10:00:00Z',
          status: 'parsed',
          warnings: [],
        },
      },
    ],
    provenance: [
      {
        dataSourceId: 'ds-001',
        artifactPath: 'C:/Windows/System32/ntoskrnl.exe',
        parser: 'metadata.extension_path',
        parsedAt: '2026-06-01T10:00:00Z',
        status: 'parsed',
        warnings: [],
      },
    ],
  },
  {
    category: 'Documents',
    fileCount: 1,
    totalSize: 4096,
    status: 'parsed',
    warnings: [],
    files: [
      {
        fileId: 'file-doc-1',
        path: 'C:/Users/Admin/Documents/Project_Alpha.doc',
        name: 'Project_Alpha.doc',
        size: 4096,
        fileType: 'Office',
        magicDescription: 'Office Document',
        provenance: {
          dataSourceId: 'ds-001',
          artifactPath: 'C:/Users/Admin/Documents/Project_Alpha.doc',
          parser: 'metadata.extension_path',
          parsedAt: '2026-06-01T10:00:00Z',
          status: 'parsed',
          warnings: [],
        },
      },
    ],
    provenance: [
      {
        dataSourceId: 'ds-001',
        artifactPath: 'C:/Users/Admin/Documents/Project_Alpha.doc',
        parser: 'metadata.extension_path',
        parsedAt: '2026-06-01T10:00:00Z',
        status: 'parsed',
        warnings: [],
      },
    ],
  },
  {
    category: 'Other',
    fileCount: 1,
    totalSize: 1100000,
    status: 'parsed',
    warnings: ['浠呭垎鏋愬墠 1000 涓枃浠讹紱鏁版嵁婧愬寘鍚?12844 涓枃浠躲€?'],
    files: [
      {
        fileId: 'file-hal-dll',
        path: 'C:/Windows/System32/hal.dll',
        name: 'hal.dll',
        size: 1100000,
        fileType: 'Unknown',
        magicDescription: 'Unknown file type',
        provenance: {
          dataSourceId: 'ds-001',
          artifactPath: 'C:/Windows/System32/hal.dll',
          parser: 'metadata.extension_path',
          parsedAt: '2026-06-01T10:00:00Z',
          status: 'parsed',
          warnings: [],
        },
      },
    ],
    provenance: [
      {
        dataSourceId: 'ds-001',
        artifactPath: 'C:/Windows/System32/hal.dll',
        parser: 'metadata.extension_path',
        parsedAt: '2026-06-01T10:00:00Z',
        status: 'parsed',
        warnings: [],
      },
    ],
  },
];

export const evidenceClassificationSummary: EvidenceClassificationSummary = {
  status: 'candidateFound',
  generatedAt: '2026-06-01T10:00:00Z',
  warnings: [],
  totals: {
    categoryCount: 8,
    candidateFileCount: 13,
    totalSize: 129105920,
    artifactCount: 12,
  },
  categories: [
    {
      category: 'SystemInformation',
      displayName: '绯荤粺淇℃伅',
      status: 'parsed',
      fileCount: 2,
      totalSize: 9306112,
      artifactCount: 1,
      confidence: 0.95,
      warnings: [],
      sources: [
        {
          fileId: 'file-system',
          path: 'Windows/System32/config/SYSTEM',
          size: 4096,
          evidenceKind: 'registry_hive',
          parser: 'registry.system_info',
          status: 'parsed',
          artifactCount: 1,
          warnings: [],
        },
        {
          fileId: 'file-software',
          path: 'Windows/System32/config/SOFTWARE',
          size: 9302016,
          evidenceKind: 'registry_hive',
          parser: 'registry.system_info',
          status: 'candidateFound',
          artifactCount: 0,
          warnings: [],
        },
      ],
      provenance: [
        {
          dataSourceId: 'ds-001',
          artifactPath: 'Windows/System32/config/SYSTEM',
          parser: 'registry.system_info',
          parsedAt: '2026-06-01T10:00:00Z',
          status: 'parsed',
          warnings: [],
        },
      ],
    },
    {
      category: 'EventLogs',
      displayName: '浜嬩欢鏃ュ織',
      status: 'candidateFound',
      fileCount: 1,
      totalSize: 2166784,
      artifactCount: 0,
      confidence: 0.65,
      warnings: ['宸插彂鐜板€欓€夋枃浠讹紱EVTX 鍏ㄩ噺浜嬩欢瑙ｆ瀽涓嶅湪 v1 榛樿浠诲姟鍐呫€?'],
      sources: [
        {
          fileId: 'file-system-evtx',
          path: 'Windows/System32/winevt/Logs/System.evtx',
          size: 2166784,
          evidenceKind: 'event_log',
          parser: 'evtx.boot_shutdown',
          status: 'candidateFound',
          artifactCount: 0,
          warnings: [],
        },
      ],
      provenance: [],
    },
    {
      category: 'ProgramExecution',
      displayName: '绋嬪簭鎵ц',
      status: 'parsed',
      fileCount: 1,
      totalSize: 98304,
      artifactCount: 2,
      confidence: 0.95,
      warnings: [],
      sources: [
        {
          fileId: 'file-prefetch',
          path: 'Windows/Prefetch/CMD.EXE-12345678.pf',
          size: 98304,
          evidenceKind: 'execution_artifact',
          parser: 'prefetch.amcache.shimcache',
          status: 'parsed',
          artifactCount: 2,
          warnings: [],
        },
      ],
      provenance: [
        {
          dataSourceId: 'ds-001',
          artifactPath: 'Windows/Prefetch/CMD.EXE-12345678.pf',
          parser: 'prefetch.amcache.shimcache',
          parsedAt: '2026-06-01T10:00:00Z',
          status: 'parsed',
          warnings: [],
        },
      ],
    },
    {
      category: 'UserActivity',
      displayName: '鐢ㄦ埛娲诲姩',
      status: 'candidateFound',
      fileCount: 1,
      totalSize: 4096,
      artifactCount: 0,
      confidence: 0.65,
      warnings: [],
      sources: [
        {
          fileId: 'file-lnk',
          path: 'Users/Admin/AppData/Roaming/Microsoft/Windows/Recent/demo.lnk',
          size: 4096,
          evidenceKind: 'user_activity',
          parser: 'lnk.jumplist.shellbags',
          status: 'candidateFound',
          artifactCount: 0,
          warnings: [],
        },
      ],
      provenance: [],
    },
    {
      category: 'Registry',
      displayName: '娉ㄥ唽琛?',
      status: 'parsed',
      fileCount: 3,
      totalSize: 18612224,
      artifactCount: 4,
      confidence: 0.92,
      warnings: [],
      sources: [
        {
          fileId: 'file-system',
          path: 'Windows/System32/config/SYSTEM',
          size: 4096,
          evidenceKind: 'registry_hive',
          parser: 'registry.key_values',
          status: 'parsed',
          artifactCount: 2,
          warnings: [],
        },
        {
          fileId: 'file-ntuser',
          path: 'Users/Admin/NTUSER.DAT',
          size: 9310208,
          evidenceKind: 'registry_hive',
          parser: 'registry.user_hive',
          status: 'parsed',
          artifactCount: 2,
          warnings: [],
        },
      ],
      provenance: [
        {
          dataSourceId: 'ds-001',
          artifactPath: 'Users/Admin/NTUSER.DAT',
          parser: 'registry.user_hive',
          parsedAt: '2026-06-01T10:10:00Z',
          status: 'parsed',
          warnings: [],
        },
      ],
    },
    {
      category: 'BrowserHistory',
      displayName: '娴忚鍣ㄨ褰?',
      status: 'parsed',
      fileCount: 3,
      totalSize: 26869760,
      artifactCount: 5,
      confidence: 0.9,
      warnings: ['Chrome/Edge History 涓?Firefox places.sqlite 鍧囨寜鍙鍓湰瑙ｆ瀽銆?'],
      sources: [
        {
          fileId: 'file-chrome-history',
          path: 'Users/Admin/AppData/Local/Google/Chrome/User Data/Default/History',
          size: 8388608,
          evidenceKind: 'browser_history',
          parser: 'browser.chrome_history',
          status: 'parsed',
          artifactCount: 2,
          warnings: [],
        },
        {
          fileId: 'file-firefox-places',
          path: 'Users/Admin/AppData/Roaming/Mozilla/Firefox/Profiles/abcd.default/places.sqlite',
          size: 10485760,
          evidenceKind: 'browser_history',
          parser: 'browser.firefox_places',
          status: 'parsed',
          artifactCount: 2,
          warnings: [],
        },
      ],
      provenance: [
        {
          dataSourceId: 'ds-001',
          artifactPath: 'Users/Admin/AppData/Local/Google/Chrome/User Data/Default/History',
          parser: 'browser.chrome_history',
          parsedAt: '2026-06-01T10:12:00Z',
          status: 'parsed',
          warnings: [],
        },
      ],
    },
    {
      category: 'Email',
      displayName: '閭欢淇℃伅',
      status: 'parsed',
      fileCount: 2,
      totalSize: 61440,
      artifactCount: 3,
      confidence: 0.84,
      warnings: ['v1 mock 瑕嗙洊 EML/EMLX锛汸ST/OST/mbox 鐣欏緟鍚庣鎵╁睍銆?'],
      sources: [
        {
          fileId: 'file-mail-1',
          path: 'Users/Admin/Documents/incident-response.eml',
          size: 32768,
          evidenceKind: 'email_message',
          parser: 'email.eml',
          status: 'parsed',
          artifactCount: 2,
          warnings: [],
        },
      ],
      provenance: [
        {
          dataSourceId: 'ds-001',
          artifactPath: 'Users/Admin/Documents/incident-response.eml',
          parser: 'email.eml',
          parsedAt: '2026-06-01T10:14:00Z',
          status: 'parsed',
          warnings: [],
        },
      ],
    },
    {
      category: 'FileTypeInventory',
      displayName: '鏂囦欢绫诲瀷娓呭崟',
      status: 'parsed',
      fileCount: 3,
      totalSize: 11304096,
      artifactCount: 0,
      confidence: 0.75,
      warnings: ['鏂囦欢绫诲瀷娓呭崟鏉ヨ嚜 metadata-only 鍒嗙被锛涙湭璇诲彇鏂囦欢姝ｆ枃銆?'],
      sources: [],
      provenance: [
        {
          dataSourceId: '',
          artifactPath: '',
          parser: 'metadata.extension_path',
          parsedAt: '2026-06-01T10:00:00Z',
          status: 'parsed',
          warnings: ['metadata aggregate from file_entries'],
        },
      ],
    },
  ],
};

export const analysisExtractionRun: AnalysisExtractionRun = {
  status: 'parsed',
  scannedCount: 13,
  artifactCount: 12,
  timelineEventCount: 5,
  generatedAt: '2026-06-01T10:15:00Z',
  warnings: ['MOCK DATA: 缁撴瀯鍖栨彁鍙栫粨鏋滅敤浜庡墠绔泦鎴愰瑙堛€?'],
};

export const registryStructuredSummary: RegistryStructuredSummary = {
  status: 'parsed',
  generatedAt: '2026-06-01T10:10:00Z',
  warnings: [],
  hiveOverviews: [
    { hiveName: 'SYSTEM', status: 'parsed', keyValueCount: 42, extractedAt: '2026-06-01T10:08:00Z', dataSourceId: 'ds-001', sourcePath: 'Windows/System32/config/SYSTEM', txlogMerged: true, deletedKeysFound: 2 },
    { hiveName: 'SOFTWARE', status: 'parsed', keyValueCount: 89, extractedAt: '2026-06-01T10:09:00Z', dataSourceId: 'ds-001', sourcePath: 'Windows/System32/config/SOFTWARE', txlogMerged: true, deletedKeysFound: 1 },
    { hiveName: 'SAM', status: 'parsed', keyValueCount: 5, extractedAt: '2026-06-01T10:09:30Z', dataSourceId: 'ds-001', sourcePath: 'Windows/System32/config/SAM', txlogMerged: true, deletedKeysFound: 0 },
    { hiveName: 'NTUSER.DAT', status: 'parsed', keyValueCount: 27, extractedAt: '2026-06-01T10:10:00Z', dataSourceId: 'ds-001', sourcePath: 'Users/刘洋/NTUSER.DAT', txlogMerged: false, deletedKeysFound: 0 },
  ],
  samUsers: [
    { username: 'Administrator', rid: 500, ridHex: '0x1F4', groups: ['Administrators'], loginCount: 142, lastLogin: '2025-03-15T09:12:18Z', accountCreated: '2024-08-10T15:30:00Z', accountStatus: 'enabled', profilePath: 'C:\\Users\\Administrator', passwordHash: 'aad3b435b51404eeaad3b435b51404ee:31d6cfe0d16ae931b73c59d7e0c089c0', passwordHashType: 'NTLM', dataSourceId: 'ds-001', hivePath: 'SAM', keyPath: 'SAM\\Domains\\Account\\Users\\000001F4', parser: 'registry.sam' },
    { username: '刘洋', rid: 1001, ridHex: '0x3E9', groups: ['Administrators', 'Users'], loginCount: 2456, lastLogin: '2025-03-16T18:45:32Z', accountCreated: '2024-08-12T10:23:11Z', accountStatus: 'enabled', profilePath: 'C:\\Users\\刘洋', passwordHash: 'aad3b435b51404eeaad3b435b51404ee:8846f7eaee8fb117ad06bdd830b7586c', passwordHashType: 'NTLM', passwordHint: '生日+名字', dataSourceId: 'ds-001', hivePath: 'SAM', keyPath: 'SAM\\Domains\\Account\\Users\\000003E9', parser: 'registry.sam' },
    { username: 'Guest', rid: 501, ridHex: '0x1F5', groups: ['Guests'], loginCount: 0, accountStatus: 'disabled', dataSourceId: 'ds-001', hivePath: 'SAM', keyPath: 'SAM\\Domains\\Account\\Users\\000001F5', parser: 'registry.sam' },
    { username: 'DefaultAccount', rid: 503, ridHex: '0x1F7', groups: ['System Reserved'], loginCount: 0, accountStatus: 'disabled', dataSourceId: 'ds-001', hivePath: 'SAM', keyPath: 'SAM\\Domains\\Account\\Users\\000001F7', parser: 'registry.sam' },
    { username: 'WDAGUtilityAccount', rid: 504, ridHex: '0x1F8', groups: ['System Reserved'], loginCount: 0, accountStatus: 'disabled', dataSourceId: 'ds-001', hivePath: 'SAM', keyPath: 'SAM\\Domains\\Account\\Users\\000001F8', parser: 'registry.sam' },
  ],
  userAssistEntries: [
    { programPath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe', execCount: 342, lastExecTime: '2025-03-16T18:42:15Z' },
    { programPath: 'C:\\Windows\\explorer.exe', execCount: 156, lastExecTime: '2025-03-16T18:40:22Z' },
    { programPath: 'D:\\Tools\\WinRAR\\WinRAR.exe', execCount: 89, lastExecTime: '2025-03-15T14:23:45Z' },
    { programPath: 'C:\\Program Files\\WeChat\\WeChat.exe', execCount: 67, lastExecTime: '2025-03-16T17:30:12Z' },
    { programPath: 'D:\\工作文件\\财务软件.exe', execCount: 23, lastExecTime: '2025-03-14T10:15:33Z' },
    { programPath: 'C:\\Windows\\System32\\cmd.exe', execCount: 12, lastExecTime: '2025-03-13T22:45:18Z' },
    { programPath: 'D:\\下载\\suspicious_file.exe', execCount: 1, lastExecTime: '2025-03-12T03:18:42Z', isSuspicious: true, suspiciousReason: '凌晨3点执行下载目录中的可疑文件' },
  ],
  networkProfiles: [
    { ssid: 'Home-WiFi-5G', firstConnect: '2024-08-12T08:00:00Z', lastConnect: '2025-03-16T18:30:00Z', connectCount: 456, description: '家庭' },
    { ssid: 'Office-Corp', firstConnect: '2024-08-15T09:00:00Z', lastConnect: '2025-03-15T17:00:00Z', connectCount: 234, description: '办公室' },
    { ssid: 'Starbucks-Guest', firstConnect: '2025-01-20T14:30:00Z', lastConnect: '2025-03-10T15:45:00Z', connectCount: 12, description: '咖啡厅' },
    { ssid: 'Hotel-Beijing', firstConnect: '2025-02-05T20:00:00Z', lastConnect: '2025-02-08T10:00:00Z', connectCount: 5, description: '酒店' },
  ],
  installedSoftware: [
    { displayName: 'Google Chrome', version: '122.0.6261.112', publisher: 'Google LLC', installDate: '2024-08-12', estimatedSize: '342 MB' },
    { displayName: 'WeChat', version: '3.9.2.23', publisher: 'Tencent', installDate: '2024-08-15', estimatedSize: '256 MB' },
    { displayName: 'WinRAR', version: '6.24', publisher: 'RARLAB', installDate: '2024-09-01', estimatedSize: '12 MB' },
    { displayName: 'Python 3.11', version: '3.11.8', publisher: 'Python Software Foundation', installDate: '2024-10-15', estimatedSize: '89 MB' },
    { displayName: 'Visual Studio Code', version: '1.87.2', publisher: 'Microsoft Corporation', installDate: '2024-11-20', estimatedSize: '432 MB' },
    { displayName: 'Unknown Tool', version: '1.0.0', installDate: '2025-03-12', estimatedSize: '2 MB', isSuspicious: true },
  ],
  usbDevices: [
    { deviceName: 'Kingston DT101 G2', serialNumber: '0019E06B9C9BF971', firstConnect: '2024-09-12T14:30:00Z', lastConnect: '2025-03-10T16:45:00Z', volumeLabel: 'KINGSTON', driveLetter: 'E:', fileSystem: 'FAT32', capacity: '16 GB' },
    { deviceName: 'SanDisk Ultra', serialNumber: '4C530001190212', firstConnect: '2024-11-05T10:20:00Z', lastConnect: '2025-02-28T15:30:00Z', volumeLabel: 'SANDISK', driveLetter: 'F:', fileSystem: 'exFAT', capacity: '64 GB' },
    { deviceName: 'WD My Passport', serialNumber: '575831314138305A', firstConnect: '2024-08-20T09:00:00Z', lastConnect: '2025-01-15T14:22:00Z', volumeLabel: 'WD Backup', driveLetter: 'G:', fileSystem: 'NTFS', capacity: '1 TB' },
    { deviceName: 'Generic Flash Disk', serialNumber: '07BC12EF00000001', firstConnect: '2025-03-12T03:15:22Z', lastConnect: '2025-03-12T03:28:45Z', driveLetter: 'H:', fileSystem: 'NTFS', capacity: '8 GB', isSuspicious: true, suspiciousReason: '凌晨时段连接 + 通用序列号 + 仅13分钟后移除' },
  ],
};

export const registryExtractionSummary: RegistryExtractionSummary = {
  status: 'parsed',
  total: 4,
  generatedAt: '2026-06-01T10:10:00Z',
  warnings: [],
  values: [
    {
      artifactId: 'reg-1',
      fileId: 'file-system',
      sourcePath: 'Windows/System32/config/SYSTEM',
      hivePath: 'SYSTEM',
      keyPath: 'ControlSet001\\Control\\ComputerName\\ComputerName',
      valueName: 'ComputerName',
      valueType: 'REG_SZ',
      data: 'BETA-LAB',
      parser: 'registry.key_values',
      createdAt: '2026-06-01T10:10:00Z',
    },
    {
      artifactId: 'reg-2',
      fileId: 'file-software',
      sourcePath: 'Windows/System32/config/SOFTWARE',
      hivePath: 'SOFTWARE',
      keyPath: 'Microsoft\\Windows NT\\CurrentVersion',
      valueName: 'ProductName',
      valueType: 'REG_SZ',
      data: 'Windows Evidence Edition 24H2',
      parser: 'registry.key_values',
      createdAt: '2026-06-01T10:10:00Z',
    },
    {
      artifactId: 'reg-3',
      fileId: 'file-ntuser',
      sourcePath: 'Users/Admin/NTUSER.DAT',
      hivePath: 'NTUSER.DAT',
      keyPath: 'Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\RunMRU',
      valueName: 'a',
      valueType: 'REG_SZ',
      data: 'cmd.exe',
      parser: 'registry.user_hive',
      createdAt: '2026-06-01T10:10:00Z',
    },
    {
      artifactId: 'reg-4',
      fileId: 'file-usrclass',
      sourcePath: 'Users/Admin/AppData/Local/Microsoft/Windows/UsrClass.dat',
      hivePath: 'UsrClass.dat',
      keyPath: 'Local Settings\\Software\\Microsoft\\Windows\\Shell\\MuiCache',
      valueName: 'C:\\Windows\\System32\\cmd.exe.FriendlyAppName',
      valueType: 'REG_SZ',
      data: 'Windows Command Processor',
      parser: 'registry.user_hive',
      createdAt: '2026-06-01T10:10:00Z',
    },
  ],
};

export const browserHistorySummary: BrowserHistorySummary = {
  status: 'parsed',
  visitTotal: 4,
  downloadTotal: 2,
  generatedAt: '2026-06-01T10:12:00Z',
  warnings: ['Chrome/Edge History 涓?Firefox places.sqlite 鏉ヨ嚜 mock 鍙鍓湰銆?'],
  visits: [
    {
      artifactId: 'browser-visit-1',
      fileId: 'file-chrome-history',
      sourcePath: 'Users/Admin/AppData/Local/Google/Chrome/User Data/Default/History',
      browser: 'Chrome',
      profile: 'Default',
      url: 'https://example.com/incident-playbook',
      title: 'Incident Response Playbook',
      visitTime: '2026-05-11T13:58:00Z',
      visitCount: 3,
    },
    {
      artifactId: 'browser-visit-2',
      fileId: 'file-edge-history',
      sourcePath: 'Users/Admin/AppData/Local/Microsoft/Edge/User Data/Profile 1/History',
      browser: 'Edge',
      profile: 'Profile 1',
      url: 'https://login.microsoftonline.com/',
      title: 'Sign in to your account',
      visitTime: '2026-05-11T14:02:10Z',
      visitCount: 2,
    },
    {
      artifactId: 'browser-visit-3',
      fileId: 'file-firefox-places',
      sourcePath: 'Users/Admin/AppData/Roaming/Mozilla/Firefox/Profiles/abcd.default/places.sqlite',
      browser: 'Firefox',
      profile: 'abcd.default',
      url: 'https://developer.mozilla.org/',
      title: 'MDN Web Docs',
      visitTime: '2026-05-11T14:08:40Z',
      visitCount: 1,
    },
    {
      artifactId: 'browser-visit-4',
      fileId: 'file-chrome-history',
      sourcePath: 'Users/Admin/AppData/Local/Google/Chrome/User Data/Default/History',
      browser: 'Chrome',
      profile: 'Default',
      url: 'https://forensics.example/search?q=prefetch',
      title: 'Forensics Search',
      visitTime: '2026-05-11T14:15:22Z',
      visitCount: 1,
    },
  ],
  downloads: [
    {
      artifactId: 'browser-download-1',
      fileId: 'file-chrome-history',
      sourcePath: 'Users/Admin/AppData/Local/Google/Chrome/User Data/Default/History',
      browser: 'Chrome',
      profile: 'Default',
      url: 'https://example.com/tools/triage.zip',
      targetPath: 'C:/Users/Admin/Downloads/triage.zip',
      startTime: '2026-05-11T14:18:00Z',
      totalBytes: 7340032,
    },
    {
      artifactId: 'browser-download-2',
      fileId: 'file-edge-history',
      sourcePath: 'Users/Admin/AppData/Local/Microsoft/Edge/User Data/Profile 1/History',
      browser: 'Edge',
      profile: 'Profile 1',
      url: 'https://example.com/report.pdf',
      targetPath: 'C:/Users/Admin/Downloads/report.pdf',
      startTime: '2026-05-11T14:21:00Z',
      totalBytes: 524288,
    },
  ],
};

export const emailExtractionSummary: EmailExtractionSummary = {
  status: 'parsed',
  total: 3,
  generatedAt: '2026-06-01T10:14:00Z',
  warnings: ['v1 浠呭睍绀?EML/EMLX 缁撴瀯鍖栧瓧娈点€?'],
  messages: [
    {
      artifactId: 'mail-1',
      fileId: 'file-mail-1',
      sourcePath: 'Users/Admin/Documents/incident-response.eml',
      sentAt: '2026-05-11T12:40:00Z',
      from: 'alice@example.com',
      to: ['dfir@example.com'],
      cc: ['lead@example.com'],
      bcc: [],
      subject: 'Initial triage notes',
      messageId: '<mock-incident-1@example.com>',
      attachments: ['triage.csv'],
      bodyPreview: 'Please review the initial triage notes and confirm whether the suspicious executable was user launched.',
    },
    {
      artifactId: 'mail-2',
      fileId: 'file-mail-2',
      sourcePath: 'Users/Admin/Documents/forwarded-alert.emlx',
      sentAt: '2026-05-11T13:05:00Z',
      from: 'soc@example.com',
      to: ['admin@example.com'],
      cc: [],
      bcc: [],
      subject: 'Forwarded security alert',
      messageId: '<mock-alert-2@example.com>',
      attachments: [],
      bodyPreview: 'Endpoint alert was forwarded from the SOC queue with the original detection summary attached inline.',
    },
    {
      artifactId: 'mail-3',
      fileId: 'file-mail-1',
      sourcePath: 'Users/Admin/Documents/incident-response.eml',
      from: 'admin@example.com',
      to: ['alice@example.com'],
      cc: [],
      bcc: [],
      subject: 'Re: Initial triage notes',
      messageId: '<mock-incident-3@example.com>',
      attachments: ['screenshot.png', 'hashes.txt'],
      bodyPreview: 'I found matching hashes in the download folder. See attached screenshot and hash list.',
    },
  ],
};

const governanceKnownLimitations: V2GovernanceSnapshot['knownLimitations'] = [
  {
    category: 'E01',
    item: '澶氭澶嶆潅鏍锋湰',
    status: 'partial',
    summary: '褰撳墠鍏紑鏍锋湰涓昏瑕嗙洊 tiny 鍗曟',
    affectedChains: ['E01'],
    sourceDoc: 'docs/known-unsupported-formats.md',
  },
  {
    category: 'NTFS',
    item: '鍏ㄩ噺鎹熷潖鎭㈠',
    status: 'notGuaranteed',
    summary: '鏋佺鎹熷潖銆佸鏉備慨澶嶅満鏅粛缂烘牱鏈笌鍥炲綊',
    affectedChains: ['NTFS'],
    sourceDoc: 'docs/known-unsupported-formats.md',
  },
  {
    category: 'FAT/exFAT',
    item: '宸插垹闄ゆ枃浠舵仮澶?',
    status: 'notGuaranteed',
    summary: '鏈疆 deleted 閲嶇偣浠呰鐩?NTFS MFT',
    affectedChains: ['FAT', 'exFAT'],
    sourceDoc: 'docs/known-unsupported-formats.md',
  },
  {
    category: 'Registry',
    item: 'transaction log 瀹屾暣閲嶆斁',
    status: 'notGuaranteed',
    summary: '褰撳墠浠?hive 鐩存帴瑙ｆ瀽涓轰富',
    affectedChains: ['Registry'],
    sourceDoc: 'docs/known-unsupported-formats.md',
  },
  {
    category: 'Prefetch',
    item: '鍏ㄧ増鏈帇缂╁彉浣?',
    status: 'partial',
    summary: '闇€瑕佺户缁ˉ鏍锋湰涓?expected baseline',
    affectedChains: ['Prefetch'],
    sourceDoc: 'docs/known-unsupported-formats.md',
  },
  {
    category: 'LNK',
    item: '鍏ㄩ噺澶嶆潅 shell item',
    status: 'partial',
    summary: '褰撳墠閲嶇偣鏄?target path 涓庢牳蹇冩椂闂村瓧娈?',
    affectedChains: ['LNK'],
    sourceDoc: 'docs/known-unsupported-formats.md',
  },
  {
    category: 'Recycle Bin',
    item: '鍏ㄦ崯鍧忔仮澶嶅満鏅?',
    status: 'notGuaranteed',
    summary: '褰撳墠浠ユ爣鍑嗙粨鏋勬彁鍙栦负涓?',
    affectedChains: ['RecycleBin'],
    sourceDoc: 'docs/known-unsupported-formats.md',
  },
  {
    category: 'Browser',
    item: '鍏ㄦ祻瑙堝櫒鍏ㄧ増鏈吋瀹?',
    status: 'notGuaranteed',
    summary: 'Edge / Chrome / Firefox 浠嶉渶鎵╁ぇ鏍锋湰',
    affectedChains: ['ChromeHistory', 'EdgeHistory', 'FirefoxHistory'],
    sourceDoc: 'docs/known-unsupported-formats.md',
  },
  {
    category: 'Email',
    item: '鍚勭被閭瀹瑰櫒鍏ㄨ鐩?',
    status: 'notGuaranteed',
    summary: '褰撳墠閲嶇偣浠嶅湪 EML / EMLX 缁撴瀯鍖栦俊鎭?',
    affectedChains: ['Email'],
    sourceDoc: 'docs/known-unsupported-formats.md',
  },
];

export const v2GovernanceSnapshot: V2GovernanceSnapshot = {
  generatedAt: '2026-06-12T00:00:00Z',
  factSources: [
    {
      area: 'verification',
      factFile: 'testdata/governance/v2-verification-catalog.json',
      factKind: 'catalog',
      derivedOutputs: ['verificationChains', 'supportMatrixEntries', 'supportMatrix'],
      lastVerifiedAt: '2026-06-12T00:00:00Z',
    },
    {
      area: 'benchmark',
      factFile: 'testdata/governance/v2-benchmark-baseline.json',
      factKind: 'baseline',
      derivedOutputs: ['benchmark.scenarios', 'benchmark.requiredChecks', 'benchmark.coveredRequiredCount'],
      lastVerifiedAt: '2026-06-12T00:00:00Z',
    },
    {
      area: 'security',
      factFile: 'testdata/governance/v2-security-taxonomy.json',
      factKind: 'taxonomy',
      derivedOutputs: ['security', 'errorTaxonomyEntries'],
      lastVerifiedAt: '2026-06-13T00:00:00Z',
    },
    {
      area: 'releasePolicy',
      factFile: 'testdata/governance/v2-release-policy.json',
      factKind: 'policy',
      derivedOutputs: ['releaseGates', 'releaseScorecard', 'runtimeSignals.correlationFamilyCoverage'],
      lastVerifiedAt: '2026-06-13T00:00:00Z',
    },
    {
      area: 'knownLimitations',
      factFile: 'testdata/governance/v2-known-limitations.json',
      factKind: 'catalog',
      derivedOutputs: ['knownLimitations', 'supportMatrix.documentedLimitCount'],
      lastVerifiedAt: '2026-06-13T00:00:00Z',
    },
    {
      area: 'runtimeResults',
      factFile: 'testdata/governance/v2-runtime-results.json',
      factKind: 'runResult',
      derivedOutputs: ['releaseGates.docsDrift', 'releaseGates.coreFixtureRegression', 'releaseGates.benchmarkThresholds', 'releaseGates.securityBaseline'],
      lastVerifiedAt: '2026-06-13T00:00:00Z',
    },
  ],
  runtimeResults: {
    checkedAt: '2026-06-13T00:00:00Z',
    checks: [
      {
        checkId: 'docs-drift',
        title: '鏂囨。闃叉紓绉?',
        status: 'passed',
        evidence: 'scripts/check-doc-drift.ps1',
        detail: 'README / AGENTS / documentation-index / Mermaid 鍥惧潡鏁伴噺涓€鑷?',
        checkedAt: '2026-06-13T00:00:00Z',
        subChecks: [
          {
            checkId: 'readme-fact-sync',
            title: 'README 浜嬪疄鍚屾',
            status: 'passed',
            evidence: 'crate/page/command counts match',
            detail: 'README 鍏抽敭浜嬪疄涓庝粨搴撴壂鎻忕粨鏋滀竴鑷?',
          },
        ],
      },
      {
        checkId: 'core-fixture-regression',
        title: '鏍稿績 fixture 鍥炲綊',
        status: 'warning',
        evidence: 'latestFixtureRun=2026-06-13T00:00:00Z; passed=6; warning=1; failed=0',
        detail: 'E01 浠嶄负 partial锛屽叾浣欐牳蹇冮摼璺€氳繃褰撳墠鍥炲綊',
        checkedAt: '2026-06-13T00:00:00Z',
        subChecks: [
          {
            checkId: 'e01-fixture',
            title: 'E01 fixture',
            status: 'warning',
            evidence: 'tiny.E01 partial coverage',
            detail: 'E01 浠嶇己澶嶆潅澶氭涓庢洿澶氬叕寮€鏍锋湰',
          },
        ],
      },
      {
        checkId: 'benchmark-thresholds',
        title: 'Benchmark 闃堝€?',
        status: 'warning',
        evidence: 'latestBenchmarkRun=2026-06-12T00:00:00Z; coveredRequired=3; missingRequired=3; exceededRequired=0',
        detail: '浠嶇己灏?medium 鏃堕棿绾跨瓫閫夈€乴arge 鏂囦欢鏍戦灞曞紑銆乴arge 鎼滅储鐑煡璇?',
        checkedAt: '2026-06-13T00:00:00Z',
        subChecks: [
          {
            checkId: 'large-search',
            title: 'large 鎼滅储鐑煡璇?',
            status: 'warning',
            evidence: 'missing benchmark record',
            detail: '浠嶆湭浜х敓鏈€杩戜竴娆″ぇ鏍锋湰鐑煡璇㈣褰?',
          },
        ],
      },
      {
        checkId: 'security-baseline',
        title: '瀹夊叏鍩虹嚎',
        status: 'passed',
        evidence: 'latestSecurityRun=2026-06-13T00:00:00Z; pathGuard=true; stdioWhitelist=true; sseHttpsOnly=true; embeddedCredentialsBlocked=true; mediaHandleScoped=true; errorRedactionEnabled=true; auditLogRequired=true',
        detail: '瀵煎嚭璺緞銆侀槻瑕嗙洊銆丮CP 鐧藉悕鍗曘€佸獟浣撳彞鏌勪笌閿欒鑴辨晱鍩虹嚎鍧囧凡閫氳繃鏈€杩戜竴娆″畨鍏ㄥ洖褰?',
        checkedAt: '2026-06-13T00:00:00Z',
        subChecks: [
          {
            checkId: 'export-path-guard',
            title: '瀵煎嚭璺緞闃叉姢',
            status: 'passed',
            evidence: 'pathGuard=true overwriteDefault=false',
            detail: '榛樿涓嶈鐩栦笖璺緞瑙勮寖鍖栭槻鎶ゅ紑鍚?',
          },
        ],
      },
    ],
  },
  verificationChains: [
    {
      chain: 'E01',
      displayName: 'E01 闀滃儚璇诲彇',
      maturity: 'beta',
      guaranteeLevel: 'bestEffort',
      fixtureTier: 'public-small',
      expectedJsonVersion: 'v1',
      verifiedSampleCount: 1,
      result: 'partial',
      notes: ['褰撳墠鍏紑鏍锋湰浠?tiny 鍗曟涓轰富銆?'],
    },
    {
      chain: 'RAW',
      displayName: 'RAW 闀滃儚璇诲彇',
      maturity: 'ga',
      guaranteeLevel: 'guaranteed',
      fixtureTier: 'public-small',
      expectedJsonVersion: 'v1',
      verifiedSampleCount: 1,
      result: 'passed',
      notes: ['鍩虹 open/read/seek 閾捐矾绋冲畾銆?'],
    },
    {
      chain: 'NTFS',
      displayName: 'NTFS 鏂囦欢绯荤粺',
      maturity: 'beta',
      guaranteeLevel: 'bestEffort',
      fixtureTier: 'public-small + synthetic',
      expectedJsonVersion: 'v1',
      verifiedSampleCount: 2,
      result: 'passed',
      notes: ['宸茶鐩栨灇涓俱€佽鍙栦笌閮ㄥ垎 deleted/hidden/system銆?'],
    },
    {
      chain: 'FAT',
      displayName: 'FAT 鏂囦欢绯荤粺',
      maturity: 'experimental',
      guaranteeLevel: 'experimental',
      fixtureTier: 'code-path',
      expectedJsonVersion: 'v1',
      verifiedSampleCount: 0,
      result: 'pending',
      notes: ['褰撳墠浠ュ熀鏈灇涓鹃摼璺负涓汇€?'],
    },
    {
      chain: 'exFAT',
      displayName: 'exFAT 鏂囦欢绯荤粺',
      maturity: 'experimental',
      guaranteeLevel: 'experimental',
      fixtureTier: 'code-path',
      expectedJsonVersion: 'v1',
      verifiedSampleCount: 0,
      result: 'pending',
      notes: ['褰撳墠浠ュ熀鏈灇涓鹃摼璺负涓汇€?'],
    },
    {
      chain: 'EVTX',
      displayName: 'EVTX 浜嬩欢鏃ュ織',
      maturity: 'beta',
      guaranteeLevel: 'bestEffort',
      fixtureTier: 'public-small',
      expectedJsonVersion: 'v1',
      verifiedSampleCount: 1,
      result: 'passed',
      notes: ['鍩虹浜嬩欢鎶藉彇宸叉帴浣?small fixture銆?'],
    },
    {
      chain: 'Prefetch',
      displayName: 'Prefetch 鎵ц鐥曡抗',
      maturity: 'beta',
      guaranteeLevel: 'bestEffort',
      fixtureTier: 'public-small',
      expectedJsonVersion: 'v1',
      verifiedSampleCount: 1,
      result: 'passed',
      notes: ['鍙墽琛屽悕銆乺un count 宸茶繘鍏?expected JSON銆?'],
    },
    {
      chain: 'LNK',
      displayName: 'LNK 蹇嵎鏂瑰紡',
      maturity: 'beta',
      guaranteeLevel: 'bestEffort',
      fixtureTier: 'public-small',
      expectedJsonVersion: 'v1',
      verifiedSampleCount: 1,
      result: 'passed',
      notes: ['target path 涓庢牳蹇冩椂闂村瓧娈靛凡杩涘叆 expected JSON銆?'],
    },
    {
      chain: 'Registry',
      displayName: 'Registry Hive',
      maturity: 'beta',
      guaranteeLevel: 'bestEffort',
      fixtureTier: 'public-small + private-real',
      expectedJsonVersion: 'v1',
      verifiedSampleCount: 2,
      result: 'passed',
      notes: ['绯荤粺淇℃伅涓庡叧閿敭鍊奸摼璺凡鏍″噯銆?'],
    },
    {
      chain: 'RecycleBin',
      displayName: 'Recycle Bin',
      maturity: 'beta',
      guaranteeLevel: 'bestEffort',
      fixtureTier: 'public-small',
      expectedJsonVersion: 'v1',
      verifiedSampleCount: 1,
      result: 'passed',
      notes: ['鍘熻矾寰勪笌鍒犻櫎鏃堕棿閾捐矾宸叉牎鍑嗐€?'],
    },
    {
      chain: 'ChromeHistory',
      displayName: 'Chrome History',
      maturity: 'experimental',
      guaranteeLevel: 'experimental',
      fixtureTier: 'mock / partial dev sample',
      expectedJsonVersion: 'v1',
      verifiedSampleCount: 0,
      result: 'pending',
      notes: ['褰撳墠浠嶇己鍏紑 medium fixture銆?'],
    },
    {
      chain: 'EdgeHistory',
      displayName: 'Edge History',
      maturity: 'experimental',
      guaranteeLevel: 'experimental',
      fixtureTier: 'mock / partial dev sample',
      expectedJsonVersion: 'v1',
      verifiedSampleCount: 0,
      result: 'pending',
      notes: ['褰撳墠浠嶇己鍏紑 medium fixture銆?'],
    },
    {
      chain: 'FirefoxHistory',
      displayName: 'Firefox History',
      maturity: 'experimental',
      guaranteeLevel: 'experimental',
      fixtureTier: 'mock / partial dev sample',
      expectedJsonVersion: 'v1',
      verifiedSampleCount: 0,
      result: 'pending',
      notes: ['schema 宸紓浠嶉渶缁х画鏀跺彛銆?'],
    },
    {
      chain: 'Email',
      displayName: '閭欢缁撴瀯鍖栦俊鎭?',
      maturity: 'experimental',
      guaranteeLevel: 'experimental',
      fixtureTier: 'mock / partial dev sample',
      expectedJsonVersion: 'v1',
      verifiedSampleCount: 0,
      result: 'pending',
      notes: ['褰撳墠浠?EML/EMLX 涓轰富銆?'],
    },
  ],
  supportMatrix: {
    gaCount: 1,
    betaCount: 7,
    experimentalCount: 6,
    unsupportedCount: 0,
    documentedLimitCount: governanceKnownLimitations.length,
  },
  supportMatrixEntries: [
    {
      chain: 'E01',
      platform: 'Windows',
      maturity: 'beta',
      verifiedSamples: ['tiny.E01'],
      baseline: '项目内 fixture',
      guaranteeSummary: 'open/read/seek 核心行为为 bestEffort',
      notes: ['多段复杂样本待补。'],
    },
    {
      chain: 'RAW',
      platform: 'Windows',
      maturity: 'ga',
      verifiedSamples: ['tiny.raw'],
      baseline: '项目内 fixture',
      guaranteeSummary: 'open/read/seek 为 guaranteed',
      notes: ['基础链路稳定。'],
    },
    {
      chain: 'NTFS',
      platform: 'Windows',
      maturity: 'beta',
      verifiedSamples: ['tiny.raw', 'synthetic NTFS fixture'],
      baseline: 'fixture 断言 / expected.json',
      guaranteeSummary: '枚举/读取稳定，复杂 deleted 恢复为 bestEffort',
      notes: ['复杂损坏样本不足。'],
    },
    {
      chain: 'FAT',
      platform: 'Windows',
      maturity: 'experimental',
      verifiedSamples: [],
      baseline: '现有测试',
      guaranteeSummary: '基本枚举为 experimental',
      notes: ['deleted recovery 不承诺。'],
    },
    {
      chain: 'exFAT',
      platform: 'Windows',
      maturity: 'experimental',
      verifiedSamples: [],
      baseline: '现有测试',
      guaranteeSummary: '基本枚举为 experimental',
      notes: ['deleted recovery 不承诺。'],
    },
    {
      chain: 'EVTX',
      platform: 'Windows',
      maturity: 'beta',
      verifiedSamples: ['system.evtx'],
      baseline: 'tiny fixture',
      guaranteeSummary: '基础事件抽取为 bestEffort',
      notes: ['大样本待补。'],
    },
    {
      chain: 'Prefetch',
      platform: 'Windows',
      maturity: 'beta',
      verifiedSamples: ['prefetch small fixture'],
      baseline: 'expected.json / 人工对照',
      guaranteeSummary: '核心字段为 bestEffort',
      notes: ['历史版本覆盖不足。'],
    },
    {
      chain: 'LNK',
      platform: 'Windows',
      maturity: 'beta',
      verifiedSamples: ['lnk small fixture'],
      baseline: 'expected.json / 人工对照',
      guaranteeSummary: 'target path / timestamps 为 bestEffort',
      notes: ['复杂 shell item 待补。'],
    },
    {
      chain: 'Registry',
      platform: 'Windows',
      maturity: 'beta',
      verifiedSamples: ['tiny SYSTEM', 'tiny SOFTWARE'],
      baseline: 'tiny fixture / expected.json',
      guaranteeSummary: '系统信息/关键键值为 bestEffort',
      notes: ['transaction log 完整重放未承诺。'],
    },
    {
      chain: 'RecycleBin',
      platform: 'Windows',
      maturity: 'beta',
      verifiedSamples: ['recycle-bin small fixture'],
      baseline: 'expected.json',
      guaranteeSummary: '原路径/删除时间为 bestEffort',
      notes: ['损坏恢复不承诺。'],
    },
    {
      chain: 'ChromeHistory',
      platform: 'Cross-platform',
      maturity: 'experimental',
      verifiedSamples: [],
      baseline: '开发样本',
      guaranteeSummary: 'visits/downloads 基本字段为 experimental',
      notes: ['公开 medium fixture 待补。'],
    },
    {
      chain: 'EdgeHistory',
      platform: 'Cross-platform',
      maturity: 'experimental',
      verifiedSamples: [],
      baseline: '开发样本',
      guaranteeSummary: 'visits/downloads 基本字段为 experimental',
      notes: ['公开 medium fixture 待补。'],
    },
    {
      chain: 'FirefoxHistory',
      platform: 'Cross-platform',
      maturity: 'experimental',
      verifiedSamples: [],
      baseline: '开发样本',
      guaranteeSummary: 'visit 基本字段为 experimental',
      notes: ['公开 medium fixture 待补。'],
    },
    {
      chain: 'Email',
      platform: 'Cross-platform',
      maturity: 'experimental',
      verifiedSamples: [],
      baseline: '开发样本',
      guaranteeSummary: 'sender/recipients/subject 为 experimental',
      notes: ['PST/OST/mbox 不承诺。'],
    },
  ],
  knownLimitations: governanceKnownLimitations,
  benchmark: {
    hostProfile: 'Windows 11 Pro / 32GB RAM / NVMe / Rust stable',
    baselineVersion: '2026.06',
    lastVerifiedAt: '2026-06-12T00:00:00Z',
    scenarios: [
      {
        datasetLevel: 'medium',
        scenario: '鏂囦欢鏍戦灞曞紑',
        p95Ms: 800,
        memoryPeakMb: 512,
        baselineVersion: '2026.06',
      },
      {
        datasetLevel: 'medium',
        scenario: '鎼滅储鐑煡璇?',
        p95Ms: 1500,
        memoryPeakMb: 1536,
        baselineVersion: '2026.06',
      },
      {
        datasetLevel: 'large',
        scenario: '鏃堕棿绾跨瓫閫?',
        p95Ms: 5000,
        memoryPeakMb: 4096,
        baselineVersion: '2026.06',
      },
    ],
    requiredChecks: [
      {
        datasetLevel: 'medium',
        scenario: '鏂囦欢鏍戦灞曞紑',
        thresholdP95Ms: 800,
        measuredP95Ms: 800,
        status: 'covered',
      },
      {
        datasetLevel: 'medium',
        scenario: '鎼滅储鐑煡璇?',
        thresholdP95Ms: 1500,
        measuredP95Ms: 1500,
        status: 'covered',
      },
      {
        datasetLevel: 'medium',
        scenario: '鏃堕棿绾跨瓫閫?',
        thresholdP95Ms: 2000,
        status: 'missing',
      },
      {
        datasetLevel: 'large',
        scenario: '鏂囦欢鏍戦灞曞紑',
        thresholdP95Ms: 2000,
        status: 'missing',
      },
      {
        datasetLevel: 'large',
        scenario: '鎼滅储鐑煡璇?',
        thresholdP95Ms: 4000,
        status: 'missing',
      },
      {
        datasetLevel: 'large',
        scenario: '鏃堕棿绾跨瓫閫?',
        thresholdP95Ms: 5000,
        measuredP95Ms: 5000,
        status: 'covered',
      },
    ],
    coveredRequiredCount: 3,
    missingRequiredCount: 3,
    exceededRequiredCount: 0,
  },
  security: {
    exportOverwriteDefault: false,
    exportPathGuardEnabled: true,
    stdioCommandWhitelistEnforced: true,
    sseHttpsOnly: true,
    embeddedCredentialsBlocked: true,
    mediaHandleScoped: true,
    errorRedactionEnabled: true,
    auditLogRequired: true,
    auditEventCount: 4,
    sensitiveAuditEventCount: 3,
    recentAuditEntries: [
      {
        action: 'mcp.tool.call',
        resourceType: 'mcp',
        resourceId: 'fixture-catalog',
        createdAt: '2026-06-12T00:10:00Z',
        summary: 'status=ok; toolName=query_fixture_catalog',
        sensitive: true,
      },
      {
        action: 'file.extract',
        resourceType: 'file',
        resourceId: 'file-cmd-exe',
        createdAt: '2026-06-12T00:06:00Z',
        summary: 'status=ok; destinationFileName=cmd.exe',
        sensitive: true,
      },
    ],
    notes: [
      'SSE 浠呭厑璁?http/https锛岀姝?embedded credentials銆?',
      'stdio command 蹇呴』鏄懡浠ゅ悕鑰屼笉鏄矾寰勶紝骞舵嫆缁?NUL 瀛楄妭銆?',
      '瀵煎嚭榛樿涓嶈鐩栵紱瑕嗙洊蹇呴』鏄惧紡纭銆?',
    ],
  },
  errorTaxonomyEntries: [
    {
      category: 'validation',
      severity: 'medium',
      recoverable: true,
      examples: ['NO_ACTIVE_CASE', 'INVALID_INPUT'],
      redactionRule: 'return user-actionable message without leaking internals',
      notes: ['鍓嶇鍙洿鎺ュ紩瀵肩敤鎴蜂慨姝ｈ緭鍏ャ€?'],
    },
    {
      category: 'parser',
      severity: 'high',
      recoverable: true,
      examples: ['registry parse failed', 'prefetch decode failed'],
      redactionRule: 'hide raw bytes, stack traces, and host absolute paths',
      notes: ['闇€瑕佷繚鐣?parser family 浠ヤ究 investigator 鍒ゆ柇杈圭晫銆?'],
    },
    {
      category: 'security',
      severity: 'high',
      recoverable: false,
      examples: ['MCP policy block', 'export path traversal denied'],
      redactionRule: 'never expose credentials, tokens, or raw absolute paths',
      notes: ['瀹夊叏鎷掔粷蹇呴』淇濈暀瀹¤璁板綍銆?'],
    },
    {
      category: 'external',
      severity: 'medium',
      recoverable: true,
      examples: ['SSE connection failed', 'stdio tool exited unexpectedly'],
      redactionRule: 'summarize stderr/network cause without passing raw payload through',
      notes: ['MCP 澶栭儴閿欒闇€瑕佸拰 security block 鍖哄垎銆?'],
    },
  ],
  releaseGates: [
    {
      gateId: 'core-fixture-regression',
      title: '鏍稿績 fixture 鍥炲綊',
      status: 'warning',
      evidence: 'coreChains=7, passed=6, partialOrPending=1, failed=0, maturity[ga=1, beta=7, experimental=6, unsupported=0]',
      detail: '浠嶆湁鏈叏閲忛€氳繃閾捐矾锛欵01 闀滃儚璇诲彇銆?',
    },
    {
      gateId: 'docs-drift',
      title: '鏂囨。闃叉紓绉?',
      status: 'passed',
      evidence: 'scripts/check-doc-drift.ps1',
      detail: 'README / AGENTS / documentation-index / Mermaid 鍥惧潡鏁伴噺涓€鑷淬€?',
    },
    {
      gateId: 'benchmark-thresholds',
      title: 'Benchmark 闃堝€?',
      status: 'warning',
      evidence: 'baselineVersion=2026.06, measuredScenarios=3, missingRequired=3, exceededRequired=0',
      detail: '浠嶇己灏?benchmark 蹇呴渶鍦烘櫙锛歮edium 鏃堕棿绾跨瓫閫夈€乴arge 鏂囦欢鏍戦灞曞紑銆乴arge 鎼滅储鐑煡璇€?',
    },
    {
      gateId: 'security-baseline',
      title: '瀹夊叏鍩虹嚎',
      status: 'passed',
      evidence: 'pathGuard=true, stdioWhitelist=true, sseHttpsOnly=true, embeddedCredentialsBlocked=true, mediaHandleScoped=true, errorRedactionEnabled=true, auditLogRequired=true, overwriteDefault=false',
      detail: '瀵煎嚭璺緞銆侀槻瑕嗙洊銆丮CP銆佸獟浣撳彞鏌勪笌閿欒鑴辨晱鍩虹嚎鍧囧凡寮€鍚€?',
    },
    {
      gateId: 'correlation-family-coverage',
      title: '鍏宠仈瑙勫垯瀹舵棌瑕嗙洊',
      status: 'passed',
      evidence: 'snapshotAvailable=true, leadCount=6, coveredFamilies=5, ruleFamilies=8, highConfidenceFamilies=5',
      detail: '褰撳墠宸插舰鎴?5 / 8 涓?covered 瀹舵棌锛屽叾涓?5 涓叿澶囬珮缃俊 lead銆?',
    },
    {
      gateId: 'evidence-hash-completeness',
      title: '璇佹嵁鍝堝笇瀹屾暣鎬?',
      status: 'warning',
      evidence: 'hashed=1, pending=1',
      detail: '浠嶆湁璇佹嵁婧愬搱甯屾湭瀹屾垚锛屽彂甯冨墠蹇呴』璇存槑鍙俊杈圭晫銆?',
    },
    {
      gateId: 'runtime-failures',
      title: '杩愯鏃跺け璐ヤ换鍔?',
      status: 'warning',
      evidence: 'runningJobCount=1, partialJobCount=1, failedJobCount=0, warningDataSourceCount=1',
      detail: '褰撳墠浠嶆湁杩愯涓殑浠诲姟锛屽彂甯冨€欓€夊墠闇€绛夊緟绋冲畾鏀舵暃銆?',
    },
  ],
  releaseScorecard: {
    totalScore: 80,
    grade: 'B',
    verificationScore: 22,
    correlationScore: 21,
    performanceScore: 15,
    securityScore: 22,
    breakdown: [
      {
        dimension: 'verification',
        maxScore: 30,
        actualScore: 22,
        deductions: ['fixture coverage gap', 'evidence hash gap', 'warning gate gap'],
      },
      {
        dimension: 'correlation',
        maxScore: 25,
        actualScore: 21,
        deductions: ['fixture gap', 'provenance warning gap'],
      },
      {
        dimension: 'performance',
        maxScore: 20,
        actualScore: 15,
        deductions: ['benchmark coverage gap', 'runtime warning gap', 'partial job gap'],
      },
      {
        dimension: 'security',
        maxScore: 25,
        actualScore: 22,
        deductions: ['evidence hash gap', 'warning gate gap'],
      },
    ],
    blockers: ['浠嶆湁璇佹嵁婧愬搱甯屾湭瀹屾垚锛屽彂甯冨墠闇€璇存槑鍙俊杈圭晫銆?'],
    residualRisks: [
      'Browser 浠嶅浜?Beta锛岀増鏈竟鐣岄渶瑕佹寔缁洖褰掋€?',
      'Email 浠嶄负 EML/EMLX-first锛孭ST/OST 淇濇寔宸茬煡闄愬埗銆?',
      'benchmark 浠嶆湭瑕嗙洊鍏ㄩ儴 medium/large 闃堝€煎満鏅€?',
      '褰撳墠妗堜欢鍚?provenance warning锛岄渶鍦?investigator 瑙嗗浘鏄惧紡鎻愮ず銆?',
    ],
  },
  runtimeSignals: {
    dataSourceCount: 2,
    hashedDataSourceCount: 1,
    pendingHashDataSourceCount: 1,
    warningDataSourceCount: 1,
    runningJobCount: 1,
    partialJobCount: 1,
    failedJobCount: 0,
    reportCount: 2,
    correlationSnapshotAvailable: true,
    correlationLeadCount: 6,
    correlationHighConfidenceLeadCount: 5,
    correlationReviewLeadCount: 3,
    correlationClusterCount: 5,
    correlationRuleFamilyCount: 8,
    correlationCoveredFamilyCount: 5,
    correlationHighConfidenceFamilyCount: 5,
    correlationFamilyCoverage: [
      {
        family: 'LNK',
        displayName: 'LNK',
        status: 'covered',
        leadCount: 1,
        highConfidenceLeadCount: 1,
        reviewLeadCount: 0,
        clusterCount: 1,
        sampleSignals: ['LNK 鐩爣璺緞鍛戒腑鏂囦欢璺緞'],
      },
      {
        family: 'Prefetch',
        displayName: 'Prefetch',
        status: 'missing',
        leadCount: 0,
        highConfidenceLeadCount: 0,
        reviewLeadCount: 0,
        clusterCount: 0,
        sampleSignals: [],
      },
      {
        family: 'Registry',
        displayName: 'Registry',
        status: 'missing',
        leadCount: 0,
        highConfidenceLeadCount: 0,
        reviewLeadCount: 0,
        clusterCount: 0,
        sampleSignals: [],
      },
      {
        family: 'RecycleBin',
        displayName: 'Recycle Bin',
        status: 'covered',
        leadCount: 1,
        highConfidenceLeadCount: 1,
        reviewLeadCount: 1,
        clusterCount: 1,
        sampleSignals: ['Recycle Bin 鍘熻矾寰勫懡涓凡鍒犻櫎鏂囦欢銆?'],
      },
      {
        family: 'BrowserDownload',
        displayName: 'Browser Download',
        status: 'covered',
        leadCount: 1,
        highConfidenceLeadCount: 1,
        reviewLeadCount: 1,
        clusterCount: 1,
        sampleSignals: ['娴忚鍣ㄤ笅杞界洰鏍囪矾寰勫懡涓枃浠惰矾寰勩€?'],
      },
      {
        family: 'BrowserHistory',
        displayName: 'Browser History',
        status: 'covered',
        leadCount: 1,
        highConfidenceLeadCount: 1,
        reviewLeadCount: 1,
        clusterCount: 0,
        sampleSignals: [
          'BrowserHistory 鏍囬鎴?URL 鍛戒腑鏂囦欢鍚嶃€?',
          'BrowserHistory 鍦?24 灏忔椂绐楀彛鍐呭懡涓偦杩戞椂闂寸嚎 REPORT_OPENED銆?',
        ],
      },
      {
        family: 'EmailMessage',
        displayName: 'Email',
        status: 'missing',
        leadCount: 0,
        highConfidenceLeadCount: 0,
        reviewLeadCount: 0,
        clusterCount: 0,
        sampleSignals: [],
      },
      {
        family: 'JumpList',
        displayName: 'JumpList',
        status: 'covered',
        leadCount: 1,
        highConfidenceLeadCount: 1,
        reviewLeadCount: 1,
        clusterCount: 1,
        sampleSignals: ['JumpList 鐩爣璺緞鍛戒腑鏂囦欢璺緞銆?'],
      },
    ],
  },
};

export const v3GovernanceSnapshot: V3GovernanceSnapshot = {
  ...v2GovernanceSnapshot,
  graphStatistics: {
    nodeCountByType: { file: 42, artifact: 15, timelineEvent: 30 },
    edgeCountByType: { references: 35, correlatesWith: 12 },
    totalNodes: 87,
    totalEdges: 47,
    density: 0.0126,
    largestComponentSize: 55,
  },
  platformCoverage: {
    windowsArtifactFamilies: 12,
    linuxArtifactFamilies: 0,
    macosArtifactFamilies: 0,
    crossPlatformArtifactFamilies: 3,
    totalFamilies: 15,
    windowsFamilies: ['LNK', 'Prefetch', 'JumpList', 'RegistryValue', 'Registry', 'RecycleBin', 'EVTX', 'SRU', 'Thumbcache', 'ShellBag', 'AmCache', 'EventLog'],
    linuxFamilies: [],
    macosFamilies: [],
    crossPlatformFamilies: ['BrowserHistory', 'BrowserDownload', 'BrowserCookie'],
  },
  rulePackCoverage: {
    loadedPacks: [
      { name: 'v2-standard', version: '1.0.0', author: 'Forensics Workbench', ruleCount: 10, scope: ['correlation'] },
    ],
    totalRuleCount: 10,
    executionStatus: 'loaded',
  },
  batchStatus: {
    activeJobs: 0,
    completedJobs: 2,
    failedJobs: 0,
    queuedJobs: 0,
    totalJobs: 2,
  },
  notebookStats: {
    entryCount: 3,
    citationCount: 7,
  },
};

export const correlationSnapshot: CorrelationSnapshot = {
  generatedAt: '2026-06-12T00:00:00Z',
  nodeCount: 10,
  edgeCount: 7,
  clusterCount: 5,
  leadCount: 5,
  familyCoverage: [
    {
      family: 'LNK',
      displayName: 'LNK',
      status: 'covered',
      leadCount: 1,
      highConfidenceLeadCount: 1,
      reviewLeadCount: 0,
      clusterCount: 1,
      sampleSignals: ['LNK 鐩爣璺緞鍛戒腑鏂囦欢璺緞'],
    },
    {
      family: 'Prefetch',
      displayName: 'Prefetch',
      status: 'missing',
      leadCount: 0,
      highConfidenceLeadCount: 0,
      reviewLeadCount: 0,
      clusterCount: 0,
      sampleSignals: [],
    },
    {
      family: 'Registry',
      displayName: 'Registry',
      status: 'missing',
      leadCount: 0,
      highConfidenceLeadCount: 0,
      reviewLeadCount: 0,
      clusterCount: 0,
      sampleSignals: [],
    },
    {
      family: 'RecycleBin',
      displayName: 'Recycle Bin',
      status: 'covered',
      leadCount: 1,
      highConfidenceLeadCount: 1,
      reviewLeadCount: 1,
      clusterCount: 1,
      sampleSignals: ['Recycle Bin 鍘熻矾寰勫懡涓凡鍒犻櫎鏂囦欢銆?'],
    },
    {
      family: 'BrowserDownload',
      displayName: 'Browser Download',
      status: 'covered',
      leadCount: 1,
      highConfidenceLeadCount: 1,
      reviewLeadCount: 1,
      clusterCount: 1,
      sampleSignals: ['娴忚鍣ㄤ笅杞界洰鏍囪矾寰勫懡涓枃浠惰矾寰勩€?'],
    },
    {
      family: 'BrowserHistory',
      displayName: 'Browser History',
      status: 'covered',
      leadCount: 1,
      highConfidenceLeadCount: 1,
      reviewLeadCount: 1,
      clusterCount: 0,
      sampleSignals: [
        'BrowserHistory 鏍囬鎴?URL 鍛戒腑鏂囦欢鍚嶃€?',
        'BrowserHistory 鍦?24 灏忔椂绐楀彛鍐呭懡涓偦杩戞椂闂寸嚎 REPORT_OPENED銆?',
      ],
    },
    {
      family: 'EmailMessage',
      displayName: 'Email',
      status: 'missing',
      leadCount: 0,
      highConfidenceLeadCount: 0,
      reviewLeadCount: 0,
      clusterCount: 0,
      sampleSignals: [],
    },
    {
      family: 'JumpList',
      displayName: 'JumpList',
      status: 'covered',
      leadCount: 1,
      highConfidenceLeadCount: 1,
      reviewLeadCount: 1,
      clusterCount: 1,
      sampleSignals: ['JumpList 鐩爣璺緞鍛戒腑鏂囦欢璺緞銆?'],
    },
  ],
  nodes: [
    {
      id: 'file:file-cmd-exe',
      kind: 'file',
      title: 'cmd.exe',
      subtitle: 'C:/Windows/System32/cmd.exe',
      sourceObjectId: 'file-cmd-exe',
      relatedCount: 3,
      badges: ['system'],
      jumps: [{ route: '/files', targetId: 'file-cmd-exe', label: '鎵撳紑鏂囦欢娴忚' }],
    },
    {
      id: 'artifact:artifact-1',
      kind: 'artifact',
      title: '[MOCK] C:/Users/Admin/Desktop/cmd.lnk',
      subtitle: '[MOCK] 鐩爣璺緞: C:/Windows/System32/cmd.exe',
      sourceObjectId: 'file-cmd-lnk',
      relatedCount: 3,
      badges: ['LNK'],
      jumps: [{ route: '/artifacts', targetId: 'artifact-1', label: '鎵撳紑鐥曡抗鍒嗘瀽' }],
    },
    {
      id: 'timeline:timeline-2',
      kind: 'timelineEvent',
      title: '[MOCK] C:/Windows/tasksche.exe',
      subtitle: '2026-05-11T14:02:45Z 路 File Created',
      sourceObjectId: 'file-cmd-exe',
      relatedCount: 3,
      badges: ['File Created'],
      jumps: [{ route: '/timeline', targetId: 'timeline-2', label: 'Open Timeline' }],
    },
    {
      id: 'file:file-hidden-deleted',
      kind: 'file',
      title: '.old-secret.txt',
      subtitle: 'C:/.old-secret.txt',
      sourceObjectId: 'file-hidden-deleted',
      relatedCount: 2,
      badges: ['deleted', 'hidden'],
      jumps: [{ route: '/files', targetId: 'file-hidden-deleted', label: '鎵撳紑鏂囦欢娴忚' }],
    },
    {
      id: 'artifact:artifact-recycle',
      kind: 'artifact',
      title: '[MOCK] Recycle Bin: deleted file',
      subtitle: '[MOCK] 鍘熻矾寰? C:/.old-secret.txt',
      sourceObjectId: 'recycle-bin-i',
      relatedCount: 1,
      badges: ['RecycleBin'],
      jumps: [{ route: '/artifacts', targetId: 'artifact-recycle', label: '鎵撳紑鐥曡抗鍒嗘瀽' }],
    },
    {
      id: 'artifact:artifact-download',
      kind: 'artifact',
      title: '[MOCK] Edge download: payload.exe',
      subtitle: '[MOCK] 鐩爣璺緞: C:/Temp/payload.exe',
      sourceObjectId: 'browser-history-db',
      relatedCount: 1,
      badges: ['BrowserDownload'],
      jumps: [{ route: '/artifacts', targetId: 'artifact-download', label: '鎵撳紑鐥曡抗鍒嗘瀽' }],
    },
    {
      id: 'artifact:artifact-jumplist',
      kind: 'artifact',
      title: '[MOCK] JumpList: report.docx',
      subtitle: '[MOCK] 鐩爣璺緞: C:/Users/Admin/Documents/report.docx',
      sourceObjectId: 'jumplist-1',
      relatedCount: 1,
      badges: ['JumpList'],
      jumps: [{ route: '/artifacts', targetId: 'artifact-jumplist', label: '鎵撳紑鐥曡抗鍒嗘瀽' }],
    },
    {
      id: 'file:file-payload',
      kind: 'file',
      title: 'payload.exe',
      subtitle: 'C:/Temp/payload.exe',
      sourceObjectId: 'file-payload',
      relatedCount: 1,
      badges: [],
      jumps: [{ route: '/files', targetId: 'file-payload', label: '鎵撳紑鏂囦欢娴忚' }],
    },
    {
      id: 'file:file-report',
      kind: 'file',
      title: 'report.docx',
      subtitle: 'C:/Users/Admin/Documents/report.docx',
      sourceObjectId: 'file-report',
      relatedCount: 1,
      badges: [],
      jumps: [{ route: '/files', targetId: 'file-report', label: '鎵撳紑鏂囦欢娴忚' }],
    },
    {
      id: 'timeline:timeline-1',
      kind: 'timelineEvent',
      title: '[MOCK] Successful logon for user SYSTEM',
      subtitle: '2026-05-11T14:01:12Z 路 Logon 4624',
      sourceObjectId: 'evtx-security-4624',
      relatedCount: 1,
      badges: ['Logon 4624'],
      jumps: [{ route: '/timeline', targetId: 'timeline-1', label: 'Open Timeline' }],
    },
  ],
  edges: [
    {
      id: 'edge-1',
      kind: 'pathMatch',
      fromNodeId: 'artifact:artifact-1',
      toNodeId: 'file:file-cmd-exe',
      summary: 'LNK 鐩爣璺緞鍛戒腑鏂囦欢璺緞',
      confidence: 'direct',
    },
    {
      id: 'edge-2',
      kind: 'temporalContext',
      fromNodeId: 'timeline:timeline-2',
      toNodeId: 'file:file-cmd-exe',
      summary: '鏃堕棿绾夸簨浠跺懡涓悓涓€ source object',
      confidence: 'direct',
    },
    {
      id: 'edge-3',
      kind: 'sharedSourceObject',
      fromNodeId: 'artifact:artifact-1',
      toNodeId: 'timeline:timeline-2',
      summary: 'Artifact 涓庢椂闂寸嚎鍏变韩鍚屼竴 source object',
      confidence: 'direct',
    },
    {
      id: 'edge-4',
      kind: 'temporalContext',
      fromNodeId: 'timeline:timeline-1',
      toNodeId: 'file:file-hidden-deleted',
      summary: '绀烘剰鎬ф椂闂翠笂涓嬫枃锛岄渶 investigator 澶嶆牳',
      confidence: 'heuristic',
    },
    {
      id: 'edge-5',
      kind: 'recoveredOriginalPath',
      fromNodeId: 'artifact:artifact-recycle',
      toNodeId: 'file:file-hidden-deleted',
      summary: 'Recycle Bin 鍘熻矾寰勫懡涓凡鍒犻櫎鏂囦欢',
      confidence: 'direct',
    },
    {
      id: 'edge-6',
      kind: 'pathMatch',
      fromNodeId: 'artifact:artifact-download',
      toNodeId: 'file:file-payload',
      summary: '娴忚鍣ㄤ笅杞界洰鏍囪矾寰勫懡涓枃浠惰矾寰?',
      confidence: 'direct',
    },
    {
      id: 'edge-7',
      kind: 'pathMatch',
      fromNodeId: 'artifact:artifact-jumplist',
      toNodeId: 'file:file-report',
      summary: 'JumpList 鐩爣璺緞鍛戒腑鏂囦欢璺緞',
      confidence: 'direct',
    },
  ],
  clusters: [
    {
      id: 'cluster:file-cmd-exe',
      title: 'cmd.exe',
      summary: 'LNK 璺緞鍖归厤涓庢椂闂寸嚎鍏卞悓鍛戒腑 cmd.exe銆?',
      confidence: 'direct',
      families: ['LNK'],
      primaryFileId: 'file-cmd-exe',
      artifactCount: 1,
      timelineCount: 1,
      nodeIds: ['file:file-cmd-exe', 'artifact:artifact-1', 'timeline:timeline-2'],
      edgeIds: ['edge-1', 'edge-2', 'edge-3'],
      provenance: [
        {
          sourceKind: 'artifact',
          sourceRecordId: 'artifact-1',
          sourceLabel: 'LNK',
          producer: 'lnk',
          producerVersion: '1.0.0-mock',
          guaranteeLevel: 'bestEffort',
          warningSummary: [],
        },
        {
          sourceKind: 'timeline',
          sourceRecordId: 'timeline-2',
          sourceLabel: 'File Created',
          producer: 'timeline.macb',
          producerVersion: '1.0.0-mock',
          guaranteeLevel: 'bestEffort',
          warningSummary: [],
        },
      ],
    },
    {
      id: 'cluster:file-hidden-deleted',
      title: '.old-secret.txt',
      summary: '褰撳墠浠呭舰鎴愬崟渚ф椂闂翠笂涓嬫枃鍛戒腑锛岄渶缁撳悎鍘熷宸ヤ欢澶嶆牳銆?',
      confidence: 'weak',
      families: [],
      primaryFileId: 'file-hidden-deleted',
      artifactCount: 0,
      timelineCount: 1,
      nodeIds: ['file:file-hidden-deleted', 'timeline:timeline-1'],
      edgeIds: ['edge-4'],
      provenance: [
        {
          sourceKind: 'timeline',
          sourceRecordId: 'timeline-1',
          sourceLabel: 'Logon 4624',
          producer: 'evtx.security',
          producerVersion: '1.0.0-mock',
          guaranteeLevel: 'experimental',
          warningSummary: ['褰撳墠浠呬负 mock 绾跨储鑱氬悎鏍蜂緥銆?'],
        },
      ],
    },
    {
      id: 'cluster:rules:file-hidden-deleted',
      title: '.old-secret.txt 瑙勫垯鍛戒腑',
      summary: 'RecycleBin 瑙勫垯鍛戒腑 1 鏉¤褰曪紙璺緞 0锛屽悕绉?0锛屽師璺緞鎭㈠ 1锛夈€?',
      confidence: 'direct',
      families: ['RecycleBin'],
      primaryFileId: 'file-hidden-deleted',
      artifactCount: 1,
      timelineCount: 0,
      nodeIds: ['file:file-hidden-deleted', 'artifact:artifact-recycle'],
      edgeIds: ['edge-5'],
      provenance: [
        {
          sourceKind: 'artifact',
          sourceRecordId: 'artifact-recycle',
          sourceLabel: 'RecycleBin',
          producer: 'recyclebin',
          producerVersion: '1.0.0-mock',
          guaranteeLevel: 'bestEffort',
          warningSummary: [],
        },
      ],
    },
    {
      id: 'cluster:rules:file-payload',
      title: 'payload.exe 瑙勫垯鍛戒腑',
      summary: 'BrowserDownload 瑙勫垯鍛戒腑 1 鏉¤褰曪紙璺緞 1锛屽悕绉?0锛屽師璺緞鎭㈠ 0锛夈€?',
      confidence: 'direct',
      families: ['BrowserDownload'],
      primaryFileId: 'file-payload',
      artifactCount: 1,
      timelineCount: 0,
      nodeIds: ['file:file-payload', 'artifact:artifact-download'],
      edgeIds: ['edge-6'],
      provenance: [
        {
          sourceKind: 'artifact',
          sourceRecordId: 'artifact-download',
          sourceLabel: 'BrowserDownload',
          producer: 'browser.history',
          producerVersion: '1.0.0-mock',
          guaranteeLevel: 'experimental',
          warningSummary: [],
        },
      ],
    },
    {
      id: 'cluster:rules:file-report',
      title: 'report.docx 瑙勫垯鍛戒腑',
      summary: 'JumpList 瑙勫垯鍛戒腑 1 鏉¤褰曪紙璺緞 1锛屽悕绉?0锛屽師璺緞鎭㈠ 0锛夈€?',
      confidence: 'direct',
      families: ['JumpList'],
      primaryFileId: 'file-report',
      artifactCount: 1,
      timelineCount: 0,
      nodeIds: ['file:file-report', 'artifact:artifact-jumplist'],
      edgeIds: ['edge-7'],
      provenance: [
        {
          sourceKind: 'artifact',
          sourceRecordId: 'artifact-jumplist',
          sourceLabel: 'JumpList',
          producer: 'jumplist',
          producerVersion: '1.0.0-mock',
          guaranteeLevel: 'experimental',
          warningSummary: [],
        },
      ],
    },
  ],
  leads: [
    {
      id: 'lead:file-cmd-exe',
      title: 'cmd.exe 褰㈡垚鍏宠仈绾跨储',
      summary: 'LNK 鐩爣璺緞涓庢椂闂寸嚎鍏卞悓鍛戒腑 cmd.exe銆?',
      confidence: 'direct',
      families: ['LNK'],
      primaryFileId: 'file-cmd-exe',
      supportingNodeIds: ['artifact:artifact-1', 'timeline:timeline-2'],
      matchSignals: ['LNK 鐩爣璺緞鍛戒腑鏂囦欢璺緞', '鍏宠仈鏂囦欢鏃堕棿绾夸簨浠舵彁渚涗笂涓嬫枃'],
      jumps: [
        { route: '/files', targetId: 'file-cmd-exe', label: '鏌ョ湅鏂囦欢' },
        { route: '/artifacts', targetId: 'artifact-1', label: '鏌ョ湅鐥曡抗' },
        { route: '/timeline', targetId: 'timeline-2', label: 'Open Timeline' },
      ],
      provenance: [
        {
          sourceKind: 'artifact',
          sourceRecordId: 'artifact-1',
          sourceLabel: 'LNK',
          producer: 'lnk',
          producerVersion: '1.0.0-mock',
          guaranteeLevel: 'bestEffort',
          warningSummary: [],
        },
        {
          sourceKind: 'timeline',
          sourceRecordId: 'timeline-2',
          sourceLabel: 'File Created',
          producer: 'timeline.macb',
          producerVersion: '1.0.0-mock',
          guaranteeLevel: 'bestEffort',
          warningSummary: [],
        },
      ],
      caveats: ['鏃堕棿绾垮懡涓潵鑷姇褰卞眰锛岃В閲婃椂闇€鍥炶烦鍘熷浜嬩欢銆?'],
    },
    {
      id: 'lead:file-hidden-deleted',
      title: '.old-secret.txt 闇€瑕佽繘涓€姝ュ鏍?',
      summary: '褰撳墠浠呭舰鎴愬崟渚ц瘉鎹懡涓紝浠嶉渶缁撳悎鍘熷 artifact 涓庢枃浠舵祻瑙堢‘璁ゃ€?',
      confidence: 'weak',
      families: [],
      primaryFileId: 'file-hidden-deleted',
      supportingNodeIds: ['timeline:timeline-1'],
      matchSignals: ['鍚屼竴 source object 鍛戒腑 1 鏉?timeline'],
      jumps: [{ route: '/files', targetId: 'file-hidden-deleted', label: '鏌ョ湅鏂囦欢' }],
      provenance: [
        {
          sourceKind: 'timeline',
          sourceRecordId: 'timeline-1',
          sourceLabel: 'Logon 4624',
          producer: 'evtx.security',
          producerVersion: '1.0.0-mock',
          guaranteeLevel: 'experimental',
          warningSummary: ['浠呬綔涓?V2 鍏宠仈瑙嗗浘鏍蜂緥銆?'],
        },
      ],
      caveats: [
        'source_object_id 涓庡綋鍓嶆椂闂寸嚎璁板綍鏈舰鎴愮洿鎺ヨВ鏋愬櫒璇佹槑锛屼粎浣滀负 mock 宸ヤ綔鍙扮ず鎰忋€?',
        '闅愯棌涓庡凡鍒犻櫎鐘舵€侀渶瑕?investigator 缁撳悎鏂囦欢娴忚璇︽儏澶嶆牳銆?',
      ],
    },
    {
      id: 'lead:rules:file-hidden-deleted',
      title: '.old-secret.txt 褰㈡垚瑙勫垯鍨嬪叧鑱旂嚎绱?',
      summary: 'Recycle Bin 鍘熻矾寰勫懡涓凡鍒犻櫎鏂囦欢銆?',
      confidence: 'direct',
      families: ['RecycleBin'],
      primaryFileId: 'file-hidden-deleted',
      supportingNodeIds: ['artifact:artifact-recycle'],
      matchSignals: ['Recycle Bin 鍘熻矾寰勫懡涓凡鍒犻櫎鏂囦欢銆?'],
      jumps: [
        { route: '/files', targetId: 'file-hidden-deleted', label: '鏌ョ湅鏂囦欢' },
        { route: '/artifacts', targetId: 'artifact-recycle', label: '鏌ョ湅鐥曡抗' },
      ],
      provenance: [
        {
          sourceKind: 'artifact',
          sourceRecordId: 'artifact-recycle',
          sourceLabel: 'RecycleBin',
          producer: 'recyclebin',
          producerVersion: '1.0.0-mock',
          guaranteeLevel: 'bestEffort',
          warningSummary: [],
        },
      ],
      caveats: ['鍥炴敹绔欏師璺緞鍙嶆槧鍒犻櫎鍓嶈矾寰勫０鏄庯紝闇€缁撳悎 deleted 鏂囦欢涓庡垹闄ゆ椂闂村鏍搞€?'],
    },
    {
      id: 'lead:rules:file-payload',
      title: 'payload.exe 褰㈡垚瑙勫垯鍨嬪叧鑱旂嚎绱?',
      summary: '娴忚鍣ㄤ笅杞界洰鏍囪矾寰勫懡涓枃浠惰矾寰勩€?',
      confidence: 'direct',
      families: ['BrowserDownload'],
      primaryFileId: 'file-payload',
      supportingNodeIds: ['artifact:artifact-download'],
      matchSignals: ['娴忚鍣ㄤ笅杞界洰鏍囪矾寰勫懡涓枃浠惰矾寰勩€?'],
      jumps: [
        { route: '/files', targetId: 'file-payload', label: '鏌ョ湅鏂囦欢' },
        { route: '/artifacts', targetId: 'artifact-download', label: '鏌ョ湅鐥曡抗' },
      ],
      provenance: [
        {
          sourceKind: 'artifact',
          sourceRecordId: 'artifact-download',
          sourceLabel: 'BrowserDownload',
          producer: 'browser.history',
          producerVersion: '1.0.0-mock',
          guaranteeLevel: 'experimental',
          warningSummary: [],
        },
      ],
      caveats: ['涓嬭浇璺緞鏉ヨ嚜娴忚鍣ㄦ暟鎹簱璁板綍锛屼粛闇€缁撳悎鏂囦欢鍐呭涓庢椂闂寸嚎澶嶆牳銆?'],
    },
    {
      id: 'lead:rules:file-browser-report',
      title: 'browser-incident-report.docx 褰㈡垚瑙勫垯鍨嬪叧鑱旂嚎绱?',
      summary: 'BrowserHistory 璁块棶璁板綍涓庨偦杩戞椂闂寸嚎鍏卞悓鎸囧悜 browser-incident-report.docx銆?',
      confidence: 'strong',
      families: ['BrowserHistory'],
      primaryFileId: 'file-browser-report',
      supportingNodeIds: ['artifact:artifact-browser-history', 'timeline:timeline-browser-history'],
      matchSignals: [
        'BrowserHistory 鏍囬鎴?URL 鍛戒腑鏂囦欢鍚嶃€?',
        'BrowserHistory 鍦?24 灏忔椂绐楀彛鍐呭懡涓偦杩戞椂闂寸嚎 REPORT_OPENED銆?',
      ],
      jumps: [
        { route: '/files', targetId: 'file-browser-report', label: '鏌ョ湅鏂囦欢' },
        { route: '/artifacts', targetId: 'artifact-browser-history', label: '鏌ョ湅鐥曡抗' },
        { route: '/timeline', targetId: 'timeline-browser-history', label: 'Open Timeline' },
      ],
      provenance: [
        {
          sourceKind: 'artifact',
          sourceRecordId: 'artifact-browser-history',
          sourceLabel: 'BrowserHistory',
          producer: 'browser.history',
          producerVersion: '1.0.0-mock',
          guaranteeLevel: 'experimental',
          warningSummary: [],
        },
        {
          sourceKind: 'timeline',
          sourceRecordId: 'timeline-browser-history',
          sourceLabel: 'REPORT_OPENED',
          producer: 'timeline.note',
          producerVersion: '1.0.0-mock',
          guaranteeLevel: 'bestEffort',
          warningSummary: [],
        },
      ],
      caveats: ['BrowserHistory 鍛戒腑鍩轰簬鏍囬涓庢椂闂撮偦杩戜俊鍙凤紝浠嶉渶缁撳悎鍘熷璁块棶璁板綍澶嶆牳銆?'],
    },
    {
      id: 'lead:rules:file-report',
      title: 'report.docx 褰㈡垚瑙勫垯鍨嬪叧鑱旂嚎绱?',
      summary: 'JumpList 鐩爣璺緞鍛戒腑鏂囦欢璺緞銆?',
      confidence: 'direct',
      families: ['JumpList'],
      primaryFileId: 'file-report',
      supportingNodeIds: ['artifact:artifact-jumplist'],
      matchSignals: ['JumpList 鐩爣璺緞鍛戒腑鏂囦欢璺緞銆?'],
      jumps: [
        { route: '/files', targetId: 'file-report', label: '鏌ョ湅鏂囦欢' },
        { route: '/artifacts', targetId: 'artifact-jumplist', label: '鏌ョ湅鐥曡抗' },
      ],
      provenance: [
        {
          sourceKind: 'artifact',
          sourceRecordId: 'artifact-jumplist',
          sourceLabel: 'JumpList',
          producer: 'jumplist',
          producerVersion: '1.0.0-mock',
          guaranteeLevel: 'experimental',
          warningSummary: [],
        },
      ],
      caveats: ['JumpList 鍛戒腑渚濊禆宓屽叆寮?LNK 鎻愬彇缁撴灉锛岄渶缁撳悎鍘熷 JumpList 澶嶆牳銆?'],
    },
  ],
};

export const analysisSummary = `# 数据源分析报告
## 系统信息

- **计算机名**: BETA-LAB
- **操作系统**: Windows Evidence Edition 24H2
- **Build 号**: 26000
- **注册用户**: DFIR Team
- **时区**: China Standard Time

### 系统信息警告

- 开关机历史来自 EVTX EventLog/User32 candidate events，不等同于直接系统启动断言。

### 系统信息来源

- registry.system: Windows/System32/config/SYSTEM
- registry.software: Windows/System32/config/SOFTWARE

## 开关机历史

- 2026-06-01T08:15:00Z (eventLogStarted, EventID 6005) - EventLog 6005 candidate

## 文件分类

| 类别 | 文件数 | 总大小 | 状态 |
|------|--------|--------|------|
| Executables | 1 | 9.7 MB | 已解析 |
| Documents | 1 | 0.0 MB | 已解析 |
| Other | 1 | 1.0 MB | 已解析 |
`;

export const filesTree = [
  { id: 'tree-system32', name: 'System32', depth: 0, hasChildren: true, expanded: true, hidden: false, system: false },
  { id: 'tree-config', name: 'config', depth: 1, hasChildren: false, hidden: false, system: false },
  { id: 'tree-drivers', name: 'drivers', depth: 1, hasChildren: false, hidden: false, system: false },
  { id: 'tree-system-volume', name: 'System Volume Information', depth: 1, hasChildren: false, hidden: true, system: true },
  { id: 'tree-winevt', name: 'winevt', depth: 1, hasChildren: true, expanded: true, active: true, hidden: false, system: false },
  { id: 'tree-logs', name: 'Logs', depth: 2, hasChildren: false, hidden: false, system: false },
];

export const fileRows: FileEntryRow[] = [
  {
    id: 'file-ntoskrnl',
    path: 'C:/Windows/System32/ntoskrnl.exe',
    name: 'ntoskrnl.exe',
    entryType: 'file',
    size: 10200000,
    deleted: false,
    hidden: false,
    system: false,
    modifiedAt: '2026-05-10T14:23:01Z',
    hashSha256: '7e1d6a0d9e8d7a2fd2814b2ef06cfd8d3b0b789f7c44a11c03f47005d82fa4e0',
  },
  {
    id: 'file-cmd-exe',
    path: 'C:/Windows/System32/cmd.exe',
    name: 'cmd.exe',
    entryType: 'file',
    size: 289000,
    deleted: false,
    hidden: false,
    system: false,
    modifiedAt: '2025-11-20T09:11:00Z',
    accessedAt: '2026-05-15T10:02:11Z',
    changedAt: '2025-11-20T09:11:00Z',
    createdAt: '2024-03-01T12:00:00Z',
    hashSha256: '2d7c4fd1ab783f91688fc2cdbf951a94544d45ef09c9cf63365b4de6b9f10d52',
  },
  {
    id: 'file-hal-dll',
    path: 'C:/Windows/System32/hal.dll',
    name: 'hal.dll',
    entryType: 'file',
    size: 1100000,
    deleted: false,
    hidden: false,
    system: false,
    modifiedAt: '2026-02-15T11:44:22Z',
    hashSha256: '9c62cd5f0a36e9385331d562d3e0e0518ed27af0d22e09b0586d2d9b4c48de8a',
  },
  {
    id: 'file-pagefile',
    path: 'C:/pagefile.sys',
    name: 'pagefile.sys',
    entryType: 'file',
    size: 2147483648,
    ext: 'sys',
    deleted: false,
    hidden: true,
    system: true,
    modifiedAt: '2026-05-12T06:00:00Z',
  },
  {
    id: 'file-deleted-log',
    path: 'C:/Windows/System32/deleted.log',
    name: 'deleted.log',
    entryType: 'file',
    size: 4096,
    ext: 'log',
    deleted: true,
    hidden: false,
    system: false,
    modifiedAt: '2026-05-11T10:00:00Z',
  },
  {
    id: 'file-hidden-deleted',
    path: 'C:/.old-secret.txt',
    name: '.old-secret.txt',
    entryType: 'file',
    size: 2048,
    ext: 'txt',
    deleted: true,
    hidden: true,
    system: false,
    modifiedAt: '2026-05-09T08:00:00Z',
  },
];


export const searchHits: SearchHit[] = [
  {
    fileId: 'file-doc-1',
    path: 'C:/Users/Admin/Documents/Project_Alpha.doc',
    score: 0.98,
    snippets: [
      {
        text: 'CONFIDENTIAL: The upcoming merger with GlobalCorp will be announced on May 20th.',
        highlights: [{ start: 40, end: 50 }],
      },
    ],
  },
  {
    fileId: 'file-doc-2',
    path: 'C:/Data/Financials_Q1.xls',
    score: 0.72,
    snippets: [{ text: 'Q1 Revenue sheet 4...', highlights: [] }],
  },
];

export const timelineEvents: TimelineEventDto[] = [
  {
    id: 'timeline-1',
    sourceObjectId: 'evtx-security-4624',
    eventType: 'Logon 4624',
    ts: '2026-05-11T14:01:12Z',
    title: '[MOCK] Successful logon for user SYSTEM',
    description: 'MOCK TIMELINE: 妫€娴嬪埌鎴愬姛鐧诲綍浜嬩欢銆?',
    parserId: 'evtx.security',
    parserVersion: '1.0.0-mock',
    confidence: 0.91,
    sourceAttribution: 'MOCK SOURCE: Windows/System32/winevt/Logs/Security.evtx',
    attrs: { source: 'Security.evtx' },
  },
  {
    id: 'timeline-2',
    sourceObjectId: 'file-cmd-exe',
    eventType: 'File Created',
    ts: '2026-05-11T14:02:45Z',
    title: '[MOCK] C:/Windows/tasksche.exe',
    description: 'MOCK TIMELINE: 鍦ㄥ嵎鏍圭洰褰曟娴嬪埌鏂囦欢鍒涘缓銆傜枒浼兼湁鏁堣浇鑽锋姇鏀俱€?',
    parserId: 'timeline.macb',
    parserVersion: '1.0.0-mock',
    confidence: 0.83,
    sourceAttribution: 'MOCK SOURCE: $MFT / $STANDARD_INFORMATION',
    attrs: { source: 'File System' },
  },
  {
    id: 'timeline-3',
    sourceObjectId: 'evtx-system-7045',
    eventType: 'Service 7045',
    ts: '2026-05-11T14:03:10Z',
    title: '[MOCK] New service installed: mssecsvc2.0',
    description: 'MOCK TIMELINE: 妫€娴嬪埌鏂版湇鍔″畨瑁呫€?',
    parserId: 'evtx.system',
    parserVersion: '1.0.0-mock',
    confidence: 0.88,
    sourceAttribution: 'MOCK SOURCE: Windows/System32/winevt/Logs/System.evtx',
    attrs: { source: 'System.evtx' },
  },
];

export const artifactFamilies = ['Prefetch', 'Amcache', 'Shimcache', 'LNK', 'JumpLists', 'UserAssist'];

export const artifactRows: ArtifactRow[] = [
  {
    id: 'artifact-1',
    artifactType: 'LNK',
    title: '[MOCK] C:/Users/Admin/Desktop/cmd.lnk',
    summary: '[MOCK] 鐩爣璺緞: C:/Windows/System32/cmd.exe',
    createdAt: '2026-01-10T09:12:00Z',
    extractorId: 'lnk',
    extractorVersion: '1.0.0-mock',
    confidence: 0.94,
    sourceAttribution: 'MOCK SOURCE: C:/Users/Admin/Desktop/cmd.lnk',
    attrs: { targetPath: 'C:/Windows/System32/cmd.exe', arguments: '-' },
  },
  {
    id: 'artifact-2',
    artifactType: 'LNK',
    title: '[MOCK] C:/Users/Admin/Recent/payload.lnk',
    summary: '[MOCK] 鐩爣璺緞: C:/Temp/payload.exe',
    createdAt: '2026-05-11T14:05:22Z',
    extractorId: 'lnk',
    extractorVersion: '1.0.0-mock',
    confidence: 0.97,
    sourceAttribution: 'MOCK SOURCE: C:/Users/Admin/Recent/payload.lnk',
    attrs: {
      targetPath: 'C:/Temp/payload.exe',
      arguments: '-hidden -execute',
      driveType: 'Fixed (3)',
      volumeSerial: 'A1B2-C3D4',
      machineId: 'DESKTOP-X921',
    },
  },
];

export const reportTemplates: ReportTemplate[] = [
  { id: 'summary', name: 'Summary', description: 'Key findings, timeline and affected assets, PDF format.' },
  { id: 'detailed', name: 'Detailed', description: 'All technical traces, full timeline and extracted strings, HTML/JSON format.' },
  { id: 'ioc', name: 'IOC Export', description: 'STIX/CSV export for hashes, IP addresses and domains.' },
];

export const reportHistory: ReportHistoryItem[] = [
  {
    id: 'report-1',
    fileName: 'Executive_Summ_v1.pdf',
    createdBy: 'Qin Ao',
    createdAt: '2026-05-14T10:00:00Z',
    status: 'completed',
  },
  {
    id: 'report-2',
    fileName: 'IOC_List_Final.csv',
    createdBy: 'Qin Ao',
    createdAt: '2026-05-15T11:30:00Z',
    status: 'running',
    progress: 60,
  },
];

export const jobs: JobSnapshot[] = [
  {
    id: 'job-1',
    name: '瀵煎叆鏁版嵁婧?',
    scope: '鍒嗗尯 2/5',
    progress: 45,
    status: 'running',
    detail: 'Enumerating Partition 3 (NTFS) - Basic data partition',
    warningCount: 0,
    skippedCount: 0,
    failedCount: 0,
    partial: false,
    currentPartition: 'Partition 3 (NTFS) - Basic data partition',
    completedPartitions: 1,
    totalPartitions: 5,
    partitionProgress: 42,
  },
  {
    id: 'job-2',
    name: '绱㈠紩 MFT',
    scope: 'Vol_1 / $MFT',
    progress: 100,
    status: 'completed',
    detail: '瀹屾垚 (2m 14s)',
    warningCount: 2,
    skippedCount: 1,
    failedCount: 0,
    partial: true,
    currentPartition: undefined,
    completedPartitions: undefined,
    totalPartitions: undefined,
    partitionProgress: undefined,
  },
  {
    id: 'job-3',
    name: '鍝堝笇璁＄畻',
    scope: '宸插鐞?1,492,033 涓枃浠?',
    progress: 100,
    status: 'completed',
    detail: '瀹屾垚 (45m 10s)',
    warningCount: 0,
    skippedCount: 0,
    failedCount: 0,
    partial: false,
    currentPartition: undefined,
    completedPartitions: undefined,
    totalPartitions: undefined,
    partitionProgress: undefined,
  },
];

export const warnings: WarningItem[] = [
  {
    id: 'warning-1',
    title: '浜嬩欢娴佹粸鍚?',
    detail: 'timeline bucket cache 鍛戒腑鍚庣瓑寰呭洖婧愭牎楠屻€?',
  },
];

export const traces: TraceItem[] = [
  { id: 'trace-1', ts: '2026-05-16T14:08:11Z', message: 'job.started artifacts-lnk-scan' },
  { id: 'trace-2', ts: '2026-05-16T14:09:02Z', message: 'artifact.added payload.lnk' },
  { id: 'trace-3', ts: '2026-05-16T14:09:11Z', message: 'timeline.updated file-created' },
];

export const graphNodes: GraphNode[] = [
  {
    id: 'graph-node-file-1',
    caseId: 'case-2026-fx-091',
    nodeType: 'File',
    label: 'tasksche.exe',
    summary: 'C:/Windows/System32/tasksche.exe — suspicious executable',
    tags: ['suspicious', 'pe'],
    createdAt: '2026-05-16T09:20:00Z',
  },
  {
    id: 'graph-node-file-2',
    caseId: 'case-2026-fx-091',
    nodeType: 'File',
    label: 'cmd.exe',
    summary: 'C:/Windows/System32/cmd.exe — command interpreter',
    tags: ['system', 'pe'],
    createdAt: '2026-05-16T09:21:00Z',
  },
  {
    id: 'graph-node-file-3',
    caseId: 'case-2026-fx-091',
    nodeType: 'File',
    label: 'payload.dll',
    summary: 'C:/Temp/payload.dll — dropped payload',
    tags: ['suspicious', 'dropped'],
    createdAt: '2026-05-16T09:22:00Z',
  },
  {
    id: 'graph-node-artifact-1',
    caseId: 'case-2026-fx-091',
    nodeType: 'Artifact',
    label: 'Prefetch: TASKSCHE.EXE',
    summary: 'Prefetch entry for tasksche.exe with 8 run count',
    tags: ['prefetch', 'execution'],
    createdAt: '2026-05-16T09:20:30Z',
  },
  {
    id: 'graph-node-artifact-2',
    caseId: 'case-2026-fx-091',
    nodeType: 'Artifact',
    label: 'LNK: cmd.lnk',
    summary: 'Shortcut targeting cmd.exe with /c payload.dll arguments',
    tags: ['lnk', 'command-line'],
    createdAt: '2026-05-16T09:21:30Z',
  },
];

export const graphEdges: GraphEdge[] = [
  {
    id: 'graph-edge-1',
    caseId: 'case-2026-fx-091',
    sourceId: 'graph-node-artifact-1',
    targetId: 'graph-node-file-1',
    edgeType: 'DerivesFrom',
    confidence: 0.95,
    provenance: 'prefetch.execution',
    createdAt: '2026-05-16T09:20:30Z',
  },
  {
    id: 'graph-edge-2',
    caseId: 'case-2026-fx-091',
    sourceId: 'graph-node-artifact-2',
    targetId: 'graph-node-file-2',
    edgeType: 'References',
    confidence: 0.9,
    provenance: 'lnk.target_path',
    createdAt: '2026-05-16T09:21:30Z',
  },
];

import type {
  BatchJob,
  BatchJobLogLine,
  BatchPhaseName,
} from '@/types/models';

export const batchJobs: BatchJob[] = [
  {
    id: 'batch-1',
    name: 'WannaCry 全量分析',
    status: 'completed',
    progress: 100,
    phases: [
      { phase: 'Mount' as BatchPhaseName, state: 'completed', progress: 100, detail: '3 data sources mounted' },
      { phase: 'Catalog' as BatchPhaseName, state: 'completed', progress: 100, detail: '1,492,033 files indexed' },
      { phase: 'ExtractArtifacts' as BatchPhaseName, state: 'completed', progress: 100, detail: '45,102 artifacts extracted' },
      { phase: 'Index' as BatchPhaseName, state: 'completed', progress: 100, detail: 'Full-text index built' },
      { phase: 'Correlate' as BatchPhaseName, state: 'completed', progress: 100, detail: '128 correlation leads found' },
      { phase: 'Export' as BatchPhaseName, state: 'completed', progress: 100, detail: 'Report exported' },
    ],
    plan: {
      name: 'WannaCry 全量分析',
      dataSourceIds: ['ds-001', 'ds-002', 'ds-003'],
      dataSourceCount: 3,
      phases: ['Mount', 'Catalog', 'ExtractArtifacts', 'Index', 'Correlate', 'Export'] as BatchPhaseName[],
      phaseCount: 6,
      resourceLimits: { memoryMb: 4096, threadCount: 8 },
    },
    createdAt: '2026-06-10T08:00:00Z',
    startedAt: '2026-06-10T08:00:05Z',
    completedAt: '2026-06-10T08:52:30Z',
    elapsedMs: 3145000,
    fileCount: 1492033,
    artifactCount: 45102,
    logTail: [
      { ts: '2026-06-10T08:52:30Z', level: 'info', message: 'Batch job completed successfully.' },
      { ts: '2026-06-10T08:52:29Z', level: 'info', message: 'Export phase finished: report.html (2.1 MB).' },
      { ts: '2026-06-10T08:45:00Z', level: 'info', message: 'Correlation found 128 leads across 18 rule families.' },
    ],
  },
  {
    id: 'batch-2',
    name: 'RDP 横向移动排查',
    status: 'running',
    progress: 62,
    phases: [
      { phase: 'Mount' as BatchPhaseName, state: 'completed', progress: 100, detail: '2 data sources mounted' },
      { phase: 'Catalog' as BatchPhaseName, state: 'completed', progress: 100, detail: '892,110 files indexed' },
      { phase: 'ExtractArtifacts' as BatchPhaseName, state: 'running', progress: 71, detail: 'Prefetch parser running... 1,203/1,704' },
      { phase: 'Index' as BatchPhaseName, state: 'pending', progress: 0, detail: '' },
      { phase: 'Correlate' as BatchPhaseName, state: 'pending', progress: 0, detail: '' },
      { phase: 'Export' as BatchPhaseName, state: 'pending', progress: 0, detail: '' },
    ],
    plan: {
      name: 'RDP 横向移动排查',
      dataSourceIds: ['ds-004', 'ds-005'],
      dataSourceCount: 2,
      phases: ['Mount', 'Catalog', 'ExtractArtifacts', 'Index', 'Correlate', 'Export'] as BatchPhaseName[],
      phaseCount: 6,
      resourceLimits: { memoryMb: 2048, threadCount: 4 },
    },
    createdAt: '2026-06-14T09:30:00Z',
    startedAt: '2026-06-14T09:30:02Z',
    elapsedMs: 1820000,
    etaMs: 1120000,
    fileCount: 892110,
    artifactCount: 1203,
    logTail: [
      { ts: '2026-06-14T10:00:30Z', level: 'info', message: 'ExtractArtifacts phase: Prefetch 1,203/1,704 (71%).' },
      { ts: '2026-06-14T09:58:12Z', level: 'warn', message: '6 files skipped due to unsupported encoding.' },
      { ts: '2026-06-14T09:45:00Z', level: 'info', message: 'Catalog phase completed: 892,110 files in 14m 58s.' },
      { ts: '2026-06-14T09:30:03Z', level: 'info', message: 'Mount phase completed: 2 data sources attached.' },
      { ts: '2026-06-14T09:30:02Z', level: 'info', message: 'Batch job started.' },
    ],
  },
  {
    id: 'batch-3',
    name: 'USB 设备痕迹提取',
    status: 'failed',
    progress: 35,
    phases: [
      { phase: 'Mount' as BatchPhaseName, state: 'completed', progress: 100, detail: '1 data source mounted' },
      { phase: 'Catalog' as BatchPhaseName, state: 'completed', progress: 100, detail: '45,200 files indexed' },
      { phase: 'ExtractArtifacts' as BatchPhaseName, state: 'failed', progress: 18, detail: 'Registry parser error: corrupted hive' },
      { phase: 'Index' as BatchPhaseName, state: 'skipped', progress: 0, detail: '' },
      { phase: 'Correlate' as BatchPhaseName, state: 'skipped', progress: 0, detail: '' },
      { phase: 'Export' as BatchPhaseName, state: 'skipped', progress: 0, detail: '' },
    ],
    plan: {
      name: 'USB 设备痕迹提取',
      dataSourceIds: ['ds-006'],
      dataSourceCount: 1,
      phases: ['Mount', 'Catalog', 'ExtractArtifacts', 'Index', 'Correlate', 'Export'] as BatchPhaseName[],
      phaseCount: 6,
      resourceLimits: { memoryMb: 1024, threadCount: 2 },
    },
    createdAt: '2026-06-13T14:00:00Z',
    startedAt: '2026-06-13T14:00:01Z',
    completedAt: '2026-06-13T14:12:30Z',
    elapsedMs: 749000,
    fileCount: 45200,
    artifactCount: 0,
    logTail: [
      { ts: '2026-06-13T14:12:30Z', level: 'error', message: 'ExtractArtifacts failed: Registry hive SOFTWARE is corrupted at offset 0x2A000.' },
      { ts: '2026-06-13T14:12:00Z', level: 'error', message: 'Registry parser encountered unexpected EOF while parsing value list.' },
      { ts: '2026-06-13T14:10:00Z', level: 'info', message: 'ExtractArtifacts phase started: 6 parsers scheduled.' },
      { ts: '2026-06-13T14:03:00Z', level: 'info', message: 'Catalog phase completed: 45,200 files in 2m 59s.' },
      { ts: '2026-06-13T14:00:02Z', level: 'info', message: 'Mount phase completed: 1 data source attached.' },
    ],
  },
];

export const graphSnapshot: GraphSnapshot = {
  nodeCountByType: { File: 3, Artifact: 2 },
  edgeCountByType: { DerivesFrom: 1, References: 1 },
  totalNodes: 5,
  totalEdges: 2,
  density: 0.2,
  largestComponentSize: 4,
};

// ── Rule Pack mock data ──

export const loadedRulePacks: import('@/types/models').RulePackSummary[] = [
  {
    id: 'rp-001',
    name: 'Windows DFIR Essentials',
    version: '2.3.1',
    author: 'Forensics Workbench Team',
    description: 'Core rule set covering common Windows forensic artifacts: Prefetch, LNK, Registry, Event Logs, and Browser History.',
    status: 'loaded',
    ruleCount: 184,
    loadedAt: '2026-06-14T08:45:00Z',
    warnings: ['3 rules use deprecated field selectors; recommend upgrading to v3.0 schema.'],
    errors: [],
    coveredFamilies: ['Prefetch', 'LNK', 'JumpList', 'Registry', 'EventLog', 'BrowserHistory', 'UserAssist'],
  },
  {
    id: 'rp-002',
    name: 'Ransomware IOC Scanner',
    version: '1.7.0',
    author: 'Community Contributed',
    description: 'Signature-based detection rules for known ransomware families including WannaCry, Ryuk, Conti, and Lockbit.',
    status: 'loaded',
    ruleCount: 312,
    loadedAt: '2026-06-14T09:10:00Z',
    warnings: [
      '18 rules reference third-party hash lists (VT Integration License required).',
      '5 rules are tagged as experimental and may produce false positives.',
    ],
    errors: [],
    coveredFamilies: ['Prefetch', 'Registry', 'EventLog', 'FileSystem', 'NetworkArtifacts'],
  },
  {
    id: 'rp-003',
    name: 'USB Device Tracing',
    version: '0.9.2-beta',
    author: 'DFIR Lab',
    description: 'Rules for detecting USB device connection history, drive serial numbers, and volume GUIDs.',
    status: 'validating',
    ruleCount: 47,
    loadedAt: '2026-06-14T09:25:00Z',
    warnings: ['Beta version: schema may change without backward compatibility.', 'Requires registry hive SOFTWARE to be accessible.'],
    errors: [],
    coveredFamilies: ['Registry', 'EventLog', 'LNK'],
  },
  {
    id: 'rp-004',
    name: 'Malformed Rule Pack',
    version: '0.1.0',
    author: 'Unknown',
    description: 'A pack with validation errors for UI testing.',
    status: 'error',
    ruleCount: 12,
    loadedAt: '2026-06-14T09:30:00Z',
    warnings: ['Pack metadata lacks required "format" field.'],
    errors: ['YAML parse error at line 42: unexpected indentation.', 'Rule "evil_rule_03" references unknown parser "not_a_real_parser".'],
    coveredFamilies: [],
  },
];

export const rulePackValidationResult: import('@/types/models').RulePackValidationResult = {
  packId: 'rp-001',
  valid: true,
  errors: [],
  warnings: ['3 rules use deprecated field selectors.'],
  coverage: {
    coveredFamilies: ['Prefetch', 'LNK', 'JumpList', 'Registry', 'EventLog', 'BrowserHistory', 'UserAssist'],
    uncoveredFamilies: ['RecycleBin', 'Thumbcache', 'SRU', 'Amcache', 'BAM', 'MFT'],
    coveragePercent: 54,
  },
};

// ── Notebook mock data ──

export const notebookEntries: import('@/types/models').NotebookEntry[] = [
  {
    id: 'nb-001',
    caseId: 'case-2026-fx-091',
    parentId: undefined,
    title: 'Initial triage observations',
    content: `## Summary

Initial examination of the evidence image reveals several indicators of compromise:

1. **Suspicious scheduled task** — \`tasksche.exe\` registered under \`HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\TaskCache\\Tasks\`
2. **Lateral movement artifacts** — Multiple RDP connection logs found, unusual for this workstation
3. **Registry persistence** — \`WanaCrypt0r\` key present in SOFTWARE hive

### Next Steps

- [ ] Run full Prefetch parser
- [ ] Correlate network connections with timeline
- [ ] Extract and analyze browser history

> ⚠️ BitLocker partition #5 is locked — cannot access until key is provided.`,
    entryType: 'finding',
    status: 'draft',
    tags: ['triage', 'ransomware', 'wannacry'],
    citationNodeIds: ['graph-node-artifact-1', 'graph-node-file-1'],
    createdAt: '2026-06-14T09:30:00Z',
    updatedAt: '2026-06-14T10:15:00Z',
  },
  {
    id: 'nb-002',
    caseId: 'case-2026-fx-091',
    parentId: 'nb-001',
    title: 'Re: Initial triage observations',
    content: 'Checked the Prefetch output — `tasksche.exe` was executed 6 times on 2026-05-15 between 08:00 and 14:30 UTC. The Prefetch hash matches known WannaCry dropper samples.',
    entryType: 'observation',
    status: 'draft',
    tags: ['prefetch', 'execution'],
    citationNodeIds: ['graph-node-file-1'],
    createdAt: '2026-06-14T10:45:00Z',
    updatedAt: '2026-06-14T10:45:00Z',
  },
  {
    id: 'nb-003',
    caseId: 'case-2026-fx-091',
    parentId: 'nb-001',
    title: 'Re: Initial triage observations',
    content: 'RDP connections to 192.168.1.50 (DC01) at 09:12 and 14:45 on 2026-05-15. Source IP is 192.168.1.23 which matches the victim workstation. Unusual RDP activity during night hours (22:30 UTC) on the same day.',
    entryType: 'observation',
    status: 'draft',
    tags: ['lateral-movement', 'rdp'],
    citationNodeIds: ['graph-node-artifact-2'],
    createdAt: '2026-06-14T11:00:00Z',
    updatedAt: '2026-06-14T11:00:00Z',
  },
  {
    id: 'nb-004',
    caseId: 'case-2026-fx-091',
    parentId: undefined,
    title: 'Email trace investigation',
    content: 'EML files recovered from the Outlook OST suggest a phishing email was opened at 07:58 on 2026-05-15. The email contained a macro-enabled spreadsheet "invoice_20260515.xlsm".',
    entryType: 'finding',
    status: 'review',
    tags: ['phishing', 'email', 'initial-access'],
    citationNodeIds: [],
    createdAt: '2026-06-14T11:20:00Z',
    updatedAt: '2026-06-14T12:00:00Z',
  },
  {
    id: 'nb-005',
    caseId: 'case-2026-fx-091',
    parentId: undefined,
    title: 'Open question: encryption scope',
    content: 'Need to determine which file extensions were encrypted. The ransomware note ("@Please_Read_Me@.txt") is present in 23 directories, but only 8 show encrypted file extensions (.WNCRY). Check if encryption was interrupted.',
    entryType: 'lead',
    status: 'draft',
    tags: ['ransomware', 'encryption', 'open-question'],
    citationNodeIds: [],
    createdAt: '2026-06-14T12:30:00Z',
    updatedAt: '2026-06-14T12:30:00Z',
  },
  {
    id: 'nb-006',
    caseId: 'case-2026-fx-091',
    parentId: 'nb-005',
    title: 'Re: Open question: encryption scope',
    content: 'Quick check: 23 ransom notes found across user directories and network shares (\\\\DC01\\Shared). 8 directories with .WNCRY files are all under C:\\Users. Encryption likely started but was terminated when the process crashed or was killed.',
    entryType: 'observation',
    status: 'draft',
    tags: ['encryption', 'ransom-note'],
    citationNodeIds: ['graph-node-file-3'],
    createdAt: '2026-06-14T13:00:00Z',
    updatedAt: '2026-06-14T13:00:00Z',
  },
];

export const notebookEntryList: import('@/types/models').NotebookEntryListItem[] = [
  {
    id: 'nb-001',
    parentId: undefined,
    title: 'Initial triage observations',
    entryType: 'finding',
    status: 'draft',
    tags: ['triage', 'ransomware', 'wannacry'],
    replyCount: 2,
    createdAt: '2026-06-14T09:30:00Z',
    updatedAt: '2026-06-14T10:15:00Z',
  },
  {
    id: 'nb-002',
    parentId: 'nb-001',
    title: 'Re: Initial triage observations',
    entryType: 'observation',
    status: 'draft',
    tags: ['prefetch', 'execution'],
    replyCount: 0,
    createdAt: '2026-06-14T10:45:00Z',
    updatedAt: '2026-06-14T10:45:00Z',
  },
  {
    id: 'nb-003',
    parentId: 'nb-001',
    title: 'Re: Initial triage observations',
    entryType: 'observation',
    status: 'draft',
    tags: ['lateral-movement', 'rdp'],
    replyCount: 0,
    createdAt: '2026-06-14T11:00:00Z',
    updatedAt: '2026-06-14T11:00:00Z',
  },
  {
    id: 'nb-004',
    parentId: undefined,
    title: 'Email trace investigation',
    entryType: 'finding',
    status: 'review',
    tags: ['phishing', 'email', 'initial-access'],
    replyCount: 0,
    createdAt: '2026-06-14T11:20:00Z',
    updatedAt: '2026-06-14T12:00:00Z',
  },
  {
    id: 'nb-005',
    parentId: undefined,
    title: 'Open question: encryption scope',
    entryType: 'lead',
    status: 'draft',
    tags: ['ransomware', 'encryption', 'open-question'],
    replyCount: 1,
    createdAt: '2026-06-14T12:30:00Z',
    updatedAt: '2026-06-14T12:30:00Z',
  },
  {
    id: 'nb-006',
    parentId: 'nb-005',
    title: 'Re: Open question: encryption scope',
    entryType: 'observation',
    status: 'draft',
    tags: ['encryption', 'ransom-note'],
    replyCount: 0,
    createdAt: '2026-06-14T13:00:00Z',
    updatedAt: '2026-06-14T13:00:00Z',
  },
];
