[package]
name = "forensics-desktop"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "forensics_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
tauri.workspace = true
tauri-plugin-dialog = "2"
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
transport.workspace = true
app-services.workspace = true
domain.workspace = true
persistence-sqlite.workspace = true
evidence-core.workspace = true
image-e01 = { path = "../../../crates/image-e01" }
fs-ntfs = { path = "../../../crates/fs-ntfs" }
rusqlite = { version = "0.31", features = ["bundled"] }
