[package]
name = "containers-pst"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
chrono.workspace = true
thiserror.workspace = true
anyhow.workspace = true
base64.workspace = true

[dev-dependencies]
tempfile = "3"
