[package]
name = "persistence-sqlite"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde_json.workspace = true
chrono.workspace = true
thiserror.workspace = true
tracing.workspace = true
domain.workspace = true
rusqlite = { workspace = true, features = ["chrono"] }
uuid.workspace = true
sha2.workspace = true
hex.workspace = true

[dev-dependencies]
tempfile.workspace = true
