[package]
name = "physical-mount"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
evidence-block.workspace = true
iscsi-target.workspace = true
rand.workspace = true
thiserror.workspace = true
tracing.workspace = true
uuid.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[dev-dependencies]
tempfile.workspace = true
