use std::collections::BTreeMap;

use ceph_wire::{
    bluestore::encode_bdev_label_block, decode_bdev_label_block, select_bdev_label,
    select_bdev_labels, BdevLabel, BdevLabelCandidate, CephUtime, CephWireError,
    BDEV_FIRST_LABEL_POSITION, BDEV_LABEL_BLOCK_SIZE, BDEV_LABEL_MAGIC, BDEV_LABEL_POSITIONS,
    BDEV_LABEL_PREFIX_LENGTH,
};
use uuid::Uuid;

const REEF_LABEL_ORACLE_HEX: &str = concat!(
    "626c756573746f726520626c6f636b206465766963650a31323334353637382d313233342d353637382d393061622d6364656630313233343536370a0201e501",
    "0000123456781234567890abcdef0123456700000008000000002255546a7a32522c040000006d61696e0d0000000a00000062666d5f626c6f636b7305000000",
    "33323736381200000062666d5f626c6f636b735f7065725f6b6579030000003132381300000062666d5f62797465735f7065725f626c6f636b04000000343039",
    "360800000062666d5f73697a650900000031333432313737323806000000626c75656673010000003109000000636570685f6673696424000000383736353433",
    "32312d343332312d383736352d626130392d66656463626139383736353419000000636570685f76657273696f6e5f7768656e5f637265617465644c00000063",
    "6570682076657273696f6e2031382e322e3820286566616335613534363037633133666135306434383232653530323432623836653665343436646629207265",
    "65662028737461626c65290a000000637265617465645f61741b000000323032362d30372d31335430333a30313a35372e3339343235315a0a0000006b765f62",
    "61636b656e6407000000726f636b736462050000006d616769631400000063657068206f736420766f6c756d652076303236090000006d6b66735f646f6e6503",
    "0000007965730500000072656164790500000072656164790600000077686f616d690100000030c8834212",
);

fn label(uuid: Uuid, version: u8, metadata: &[(&str, &str)]) -> BdevLabel {
    BdevLabel {
        osd_uuid: uuid,
        size: 8 * 1024 * 1024 * 1024,
        birth_time: CephUtime {
            seconds: 1_700_000_000,
            nanoseconds: 123_456_789,
        },
        description: "main block device".to_string(),
        metadata: metadata
            .iter()
            .map(|(key, value)| ((*key).to_string(), (*value).to_string()))
            .collect::<BTreeMap<_, _>>(),
        struct_version: version,
        struct_compat_version: 1,
    }
}

fn decode_hex(value: &str) -> Vec<u8> {
    value
        .as_bytes()
        .chunks_exact(2)
        .map(|pair| {
            let digits = std::str::from_utf8(pair).unwrap();
            u8::from_str_radix(digits, 16).unwrap()
        })
        .collect()
}

#[test]
fn label_positions_match_upstream_main() {
    assert_eq!(BDEV_LABEL_BLOCK_SIZE, 4096);
    assert_eq!(
        BDEV_LABEL_POSITIONS,
        [0, 1 << 30, 10 << 30, 100 << 30, 1000 << 30]
    );
}

#[test]
fn decodes_real_ceph_bluestore_tool_reef_label_oracle() {
    // Generated by Ceph Reef 18.2.8 ceph-osd --mkfs and independently accepted
    // by ceph-bluestore-tool show-label. The real block is zero-padded after CRC.
    let mut block = decode_hex(REEF_LABEL_ORACLE_HEX);
    assert_eq!(block.len(), 555);
    block.resize(BDEV_LABEL_BLOCK_SIZE, 0);

    assert_eq!(&block[..BDEV_LABEL_MAGIC.len()], BDEV_LABEL_MAGIC);
    assert_eq!(BDEV_LABEL_PREFIX_LENGTH, 60);
    assert_eq!(
        &block[..BDEV_LABEL_PREFIX_LENGTH],
        b"bluestore block device\n12345678-1234-5678-90ab-cdef01234567\n"
    );
    assert_eq!((block[60], block[61]), (2, 1));
    assert_eq!(u32::from_le_bytes(block[62..66].try_into().unwrap()), 485);

    let crc_offset = 66 + 485;
    assert_eq!(crc_offset, 551);
    assert_eq!(
        ceph_wire::crc32c::ceph_crc32c(&block[..crc_offset]),
        0x1242_83c8
    );
    assert_eq!(
        u32::from_le_bytes(block[crc_offset..crc_offset + 4].try_into().unwrap()),
        0x1242_83c8
    );

    let decoded = decode_bdev_label_block(&block).unwrap();
    assert_eq!(
        decoded.osd_uuid,
        Uuid::parse_str("12345678-1234-5678-90ab-cdef01234567").unwrap()
    );
    assert_eq!(decoded.size, 134_217_728);
    assert_eq!(decoded.birth_time.seconds, 1_783_911_714);
    assert_eq!(decoded.birth_time.nanoseconds, 743_584_378);
    assert_eq!(decoded.description, "main");
    assert_eq!(decoded.metadata.len(), 13);
    assert_eq!(
        decoded.metadata["ceph_fsid"],
        "87654321-4321-8765-ba09-fedcba987654"
    );
    assert_eq!(decoded.metadata["magic"], "ceph osd volume v026");
    assert_eq!(decoded.metadata["whoami"], "0");
}

#[test]
fn prefix_is_crc_covered_but_not_magic_validated() {
    // Upstream bluestore_bdev_label_t::decode advances by exactly 60 bytes.
    // Reef ceph-bluestore-tool accepts this same mutation after CRC repair.
    let mut block = decode_hex(REEF_LABEL_ORACLE_HEX);
    block.resize(BDEV_LABEL_BLOCK_SIZE, 0);
    block[0] = b'B';
    let crc_offset = 551;
    let crc = ceph_wire::crc32c::ceph_crc32c(&block[..crc_offset]);
    block[crc_offset..crc_offset + 4].copy_from_slice(&crc.to_le_bytes());

    assert_eq!(decode_bdev_label_block(&block).unwrap().description, "main");
}

#[test]
fn decodes_complete_v2_label_block_and_checks_crc() {
    let uuid = Uuid::parse_str("12345678-1234-5678-90ab-cdef01234567").unwrap();
    let expected = label(uuid, 2, &[("multi", "yes"), ("epoch", "42")]);
    let block = encode_bdev_label_block(&expected);
    assert_eq!(decode_bdev_label_block(&block).unwrap(), expected);

    let mut corrupt = block;
    corrupt[82] ^= 0x80;
    assert!(matches!(
        decode_bdev_label_block(&corrupt),
        Err(CephWireError::CrcMismatch { .. })
    ));
}

#[test]
fn decodes_v1_without_metadata_and_future_compatible_tail() {
    let uuid = Uuid::new_v4();
    let v1 = label(uuid, 1, &[]);
    assert_eq!(
        decode_bdev_label_block(&encode_bdev_label_block(&v1)).unwrap(),
        v1
    );

    let future = label(uuid, 3, &[("multi", "yes"), ("epoch", "8")]);
    let mut block = encode_bdev_label_block(&future);
    let payload_length = u32::from_le_bytes(block[62..66].try_into().unwrap());
    let crc_offset = 66 + payload_length as usize;
    block.splice(crc_offset..crc_offset, [0xaa, 0xbb, 0xcc]);
    block[62..66].copy_from_slice(&(payload_length + 3).to_le_bytes());
    let crc_offset = crc_offset + 3;
    let crc = ceph_wire::crc32c::ceph_crc32c(&block[..crc_offset]);
    block[crc_offset..crc_offset + 4].copy_from_slice(&crc.to_le_bytes());
    block.truncate(BDEV_LABEL_BLOCK_SIZE);

    let decoded = decode_bdev_label_block(&block).unwrap();
    assert_eq!(decoded.struct_version, 3);
    assert_eq!(decoded.metadata["epoch"], "8");
}

#[test]
fn rejects_short_or_structurally_empty_blocks() {
    assert!(matches!(
        decode_bdev_label_block(&[0; 128]),
        Err(CephWireError::UnexpectedEof { .. })
    ));
    assert!(matches!(
        decode_bdev_label_block(&[0; BDEV_LABEL_BLOCK_SIZE]),
        Err(CephWireError::UnexpectedEof { .. })
    ));
}

#[test]
fn legacy_first_position_wins_without_multi_metadata() {
    let uuid = Uuid::new_v4();
    let legacy = label(uuid, 2, &[("whoami", "3")]);
    let newer = label(uuid, 2, &[("multi", "yes"), ("epoch", "99")]);
    let selected = select_bdev_label(
        [
            (BDEV_LABEL_POSITIONS[1], newer),
            (BDEV_FIRST_LABEL_POSITION, legacy.clone()),
        ],
        Some(uuid),
    )
    .unwrap();

    assert_eq!(selected.label, legacy);
    assert!(!selected.is_multi);
    assert_eq!(selected.valid_positions, vec![0]);
}

#[test]
fn selects_highest_epoch_and_all_matching_copies() {
    let uuid = Uuid::new_v4();
    let old = label(uuid, 2, &[("multi", "yes"), ("epoch", "4")]);
    let current = label(uuid, 2, &[("multi", "yes"), ("epoch", "7")]);
    let selected = select_bdev_label(
        [
            (BDEV_LABEL_POSITIONS[0], old),
            (BDEV_LABEL_POSITIONS[1], current.clone()),
            (BDEV_LABEL_POSITIONS[2], current.clone()),
        ],
        Some(uuid),
    )
    .unwrap();

    assert_eq!(selected.label, current);
    assert_eq!(selected.epoch, Some(7));
    assert_eq!(
        selected.valid_positions,
        vec![BDEV_LABEL_POSITIONS[1], BDEV_LABEL_POSITIONS[2]]
    );
}

#[test]
fn rejects_conflicting_copies_at_the_same_epoch() {
    let uuid = Uuid::new_v4();
    let first = label(
        uuid,
        2,
        &[("multi", "yes"), ("epoch", "7"), ("whoami", "1")],
    );
    let conflicting = label(
        uuid,
        2,
        &[("multi", "yes"), ("epoch", "7"), ("whoami", "2")],
    );

    assert_eq!(
        select_bdev_label(
            [
                (BDEV_LABEL_POSITIONS[1], first),
                (BDEV_LABEL_POSITIONS[2], conflicting),
            ],
            Some(uuid),
        )
        .unwrap_err(),
        CephWireError::ConflictingLabelCopies {
            osd_uuid: uuid,
            epoch: 7,
            first_position: BDEV_LABEL_POSITIONS[1],
            conflicting_position: BDEV_LABEL_POSITIONS[2],
        }
    );
}

#[test]
fn selection_locks_uuid_and_ignores_corrupt_blocks() {
    let wanted = Uuid::new_v4();
    let other = Uuid::new_v4();
    let wanted_label = label(wanted, 2, &[("multi", "yes"), ("epoch", "3")]);
    let other_label = label(other, 2, &[("multi", "yes"), ("epoch", "100")]);
    let mut corrupt = encode_bdev_label_block(&wanted_label);
    corrupt[90] ^= 1;

    let selected = select_bdev_labels(
        [
            BdevLabelCandidate::new(BDEV_LABEL_POSITIONS[0], corrupt),
            BdevLabelCandidate::new(
                BDEV_LABEL_POSITIONS[1],
                encode_bdev_label_block(&other_label),
            ),
            BdevLabelCandidate::new(
                BDEV_LABEL_POSITIONS[2],
                encode_bdev_label_block(&wanted_label),
            ),
        ],
        Some(wanted),
    )
    .unwrap();

    assert_eq!(selected.label.osd_uuid, wanted);
    assert_eq!(selected.epoch, Some(3));
    assert_eq!(selected.valid_positions, vec![BDEV_LABEL_POSITIONS[2]]);
}

#[test]
fn multi_without_epoch_is_not_selectable() {
    let uuid = Uuid::new_v4();
    let result = select_bdev_label(
        [(
            BDEV_FIRST_LABEL_POSITION,
            label(uuid, 2, &[("multi", "yes")]),
        )],
        Some(uuid),
    );
    assert_eq!(result.unwrap_err(), CephWireError::NoValidLabel);
}
