[package]
name = "memory-windows"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
zeroize.workspace = true
memchr.workspace = true
volume-bitlocker.workspace = true

[dev-dependencies]
tempfile.workspace = true
