[package]
name = "volume-android"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
sha2.workspace = true
evidence-core.workspace = true
fs-ext4.workspace = true
fs-f2fs.workspace = true
fs-erofs.workspace = true

[dev-dependencies]
tempfile.workspace = true
image-android.workspace = true
testing.workspace = true
