pub(super) const SOURCE_MIGRATIONS: &[(&str, &str)] = &[
    ("source_001", include_str!("scripts/source_001.sql")),
    (
        "source_002_data_source_metadata",
        include_str!("scripts/source_002_data_source_metadata.sql"),
    ),
    (
        "source_003_correlation_cache",
        include_str!("scripts/source_003_correlation_cache.sql"),
    ),
    (
        "source_004_graph_node_order_index",
        include_str!("scripts/source_004_graph_node_order_index.sql"),
    ),
    (
        "source_005_ceph_osd_inventory",
        include_str!("scripts/source_005_ceph_osd_inventory.sql"),
    ),
    (
        "source_006_ceph_bluefs_inventory",
        include_str!("scripts/source_006_ceph_bluefs_inventory.sql"),
    ),
    (
        "source_007_ceph_bluefs_replay",
        include_str!("scripts/source_007_ceph_bluefs_replay.sql"),
    ),
    (
        "source_008_ceph_rocksdb_inventory",
        include_str!("scripts/source_008_ceph_rocksdb_inventory.sql"),
    ),
    (
        "source_009_ceph_sst_inventory",
        include_str!("scripts/source_009_ceph_sst_inventory.sql"),
    ),
    (
        "source_010_ceph_wal_inventory",
        include_str!("scripts/source_010_ceph_wal_inventory.sql"),
    ),
    (
        "source_011_ceph_latest_state",
        include_str!("scripts/source_011_ceph_latest_state.sql"),
    ),
    (
        "source_012_ceph_bluestore_semantics",
        include_str!("scripts/source_012_ceph_bluestore_semantics.sql"),
    ),
    (
        "source_013_ceph_bluestore_omap",
        include_str!("scripts/source_013_ceph_bluestore_omap.sql"),
    ),
    (
        "source_014_ceph_osd_device_bindings",
        include_str!("scripts/source_014_ceph_osd_device_bindings.sql"),
    ),
    (
        "source_015_ceph_bluestore_rbd_header_context",
        include_str!("scripts/source_015_ceph_bluestore_rbd_header_context.sql"),
    ),
    (
        "source_016_file_partition_index",
        include_str!("scripts/source_016_file_partition_index.sql"),
    ),
    (
        "source_017_timeline_projection_identity",
        include_str!("scripts/source_017_timeline_projection_identity.sql"),
    ),
    (
        "source_018_cephfs_metadata_inventory",
        include_str!("scripts/source_018_cephfs_metadata_inventory.sql"),
    ),
    (
        "source_019_cephfs_journal_replay",
        include_str!("scripts/source_019_cephfs_journal_replay.sql"),
    ),
    (
        "source_020_cephfs_namespace_layout",
        include_str!("scripts/source_020_cephfs_namespace_layout.sql"),
    ),
    (
        "source_021_cephfs_assembly_capability",
        include_str!("scripts/source_021_cephfs_assembly_capability.sql"),
    ),
    (
        "source_022_file_partition_index_repair",
        include_str!("scripts/source_022_file_partition_index_repair.sql"),
    ),
    (
        "source_023_deleted_recovery",
        include_str!("scripts/source_023_deleted_recovery.sql"),
    ),
    (
        "source_024_ntfs_deleted_recovery",
        include_str!("scripts/source_024_ntfs_deleted_recovery.sql"),
    ),
    (
        "source_025_file_entry_encrypted",
        include_str!("scripts/source_025_file_entry_encrypted.sql"),
    ),
    (
        "source_026_timeline_keyset_indexes",
        include_str!("scripts/source_026_timeline_keyset_indexes.sql"),
    ),
    (
        "source_027_artifact_keyset_indexes",
        include_str!("scripts/source_027_artifact_keyset_indexes.sql"),
    ),
    (
        "source_028_file_entry_read_only",
        include_str!("scripts/source_028_file_entry_read_only.sql"),
    ),
    (
        "source_029_case_graph_entity_index",
        include_str!("scripts/source_029_case_graph_entity_index.sql"),
    ),
    (
        "source_030_analysis_file_feed_index",
        include_str!("scripts/source_030_analysis_file_feed_index.sql"),
    ),
    (
        "source_031_mount_directory_index",
        include_str!("scripts/source_031_mount_directory_index.sql"),
    ),
    (
        "source_032_deleted_recovery_hashes",
        include_str!("scripts/source_032_deleted_recovery_hashes.sql"),
    ),
    (
        "source_033_timeline_case_id_index",
        include_str!("scripts/source_033_timeline_case_id_index.sql"),
    ),
];
