//! Regression test for the committed public-medium systemd journal fixture
//! (`testdata/fixtures/public-medium/linux/journal/system.journal`).
//!
//! The fixture is generated by `common::fixture_spec` and pinned by the
//! adjacent `expected.json` (see `docs/expected-json-contract.md`). The
//! `regenerate_journal_fixture` test below re-materializes the binary after
//! `fixture_spec` changes; it is `#[ignore]`d so normal CI only validates the
//! committed bytes.

mod common;

use std::fs;
use std::path::PathBuf;

use artifacts_linux::parse_journal_full;
use serde_json::Value;

use common::{
    build_journal, fixture_spec, FIXTURE_BOOT_A_HEX, FIXTURE_BOOT_B_HEX, FIXTURE_ENTRY_COUNT,
    FIXTURE_LZ4_MESSAGE, FIXTURE_XZ_MESSAGE,
};

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../testdata/fixtures/public-medium/linux/journal")
}

#[test]
fn committed_journal_fixture_matches_expected_json() {
    let dir = fixture_dir();
    let journal = fs::read(dir.join("system.journal")).expect("read committed journal fixture");
    let expected_text =
        fs::read_to_string(dir.join("expected.json")).expect("read fixture expected.json");
    let expected: Value =
        serde_json::from_str(&expected_text).expect("expected.json is valid JSON");
    let assertions = &expected[0]["expected"]["assertions"];

    let outcome = parse_journal_full(&journal).expect("committed fixture must parse");

    assert_eq!(
        outcome.entries.len(),
        assertions["entryCount"].as_u64().expect("entryCount") as usize
    );
    assert_eq!(
        outcome.skipped_compressed,
        assertions["skippedCompressed"]
            .as_u64()
            .expect("skippedCompressed")
    );
    assert_eq!(
        outcome.hash_mismatches,
        assertions["hashMismatches"]
            .as_u64()
            .expect("hashMismatches")
    );
    assert!(!outcome.truncated);

    // Every entry carries the required fields promised in expected.json.
    for entry in &outcome.entries {
        for field in assertions["requiredFields"]
            .as_array()
            .expect("requiredFields")
        {
            let name = field.as_str().expect("field name");
            assert!(
                entry.raw_fields.contains_key(name),
                "entry {:?} is missing required field {name}",
                entry.seqnum
            );
        }
    }

    let boot_ids: std::collections::HashSet<&str> = outcome
        .entries
        .iter()
        .filter_map(|entry| entry.boot_id.as_deref())
        .collect();
    assert_eq!(
        boot_ids.len(),
        assertions["distinctBootIds"]
            .as_u64()
            .expect("distinctBootIds") as usize
    );
    assert!(boot_ids.contains(FIXTURE_BOOT_A_HEX));
    assert!(boot_ids.contains(FIXTURE_BOOT_B_HEX));

    let priorities: std::collections::HashSet<u8> = outcome
        .entries
        .iter()
        .filter_map(|entry| entry.priority)
        .collect();
    assert!(
        priorities.len() as u64
            >= assertions["minDistinctPriorities"]
                .as_u64()
                .expect("minDistinctPriorities")
    );

    // Key entries pin exact timestamps/messages/pids so silent format or
    // decompression regressions fail loudly.
    let first = &outcome.entries[0];
    assert_eq!(
        first.timestamp.map(|ts| ts.timestamp_micros()),
        Some(1_700_000_000_000_000)
    );
    assert_eq!(first.priority, Some(0));
    assert_eq!(first.pid, Some(1200));
    assert_eq!(first.systemd_unit.as_deref(), Some("sshd.service"));
    assert_eq!(first.hostname.as_deref(), Some("fixture-host"));
    assert_eq!(first.boot_id.as_deref(), Some(FIXTURE_BOOT_A_HEX));
    assert_eq!(
        first.message.as_deref(),
        Some("sshd.service heartbeat cycle 0")
    );

    // The XZ-compressed long message (systemd v219 default) must decode.
    let xz_entry = &outcome.entries[10];
    assert_eq!(xz_entry.message.as_deref(), Some(FIXTURE_XZ_MESSAGE));

    // The LZ4-compressed message must decode in the same file.
    let lz4_entry = &outcome.entries[20];
    assert_eq!(lz4_entry.message.as_deref(), Some(FIXTURE_LZ4_MESSAGE));

    // First entry of the second boot.
    let boot_b_first = &outcome.entries[60];
    assert_eq!(
        boot_b_first.timestamp.map(|ts| ts.timestamp_micros()),
        Some(1_700_100_000_000_000)
    );
    assert_eq!(boot_b_first.boot_id.as_deref(), Some(FIXTURE_BOOT_B_HEX));
}

#[test]
fn committed_fixture_bytes_match_generator() {
    let journal = fs::read(fixture_dir().join("system.journal")).expect("read committed fixture");
    let regenerated = build_journal(&fixture_spec());
    assert_eq!(
        journal, regenerated,
        "committed fixture drifted from fixture_spec; regenerate it with \
         `cargo test -p artifacts-linux --test journal_fixture -- --ignored`"
    );
    assert_eq!(FIXTURE_ENTRY_COUNT, fixture_spec().entries.len());
}

/// Regenerate the committed fixture after changing `common::fixture_spec`.
/// Prints the SHA-256 to paste into the fixture README.
#[test]
#[ignore = "writes the committed fixture; run manually after fixture_spec changes"]
fn regenerate_journal_fixture() {
    let dir = fixture_dir();
    fs::create_dir_all(&dir).expect("create fixture dir");
    let bytes = build_journal(&fixture_spec());
    fs::write(dir.join("system.journal"), &bytes).expect("write fixture");
    eprintln!(
        "wrote {} bytes to {}",
        bytes.len(),
        dir.join("system.journal").display()
    );
}
