// @generated by the kernel farm merge (winbindex -> RSDS -> Microsoft PDB).
// Do not edit by hand; regenerate when the symbol collection changes.

mod part_00;
mod part_01;
mod part_02;
mod part_03;
mod part_04;
mod part_05;
mod part_06;
mod part_07;
mod part_08;
mod part_09;
mod part_10;
mod part_11;
mod part_12;
mod part_13;

/// One registry row: the only per-build facts the recovery path needs.
pub(crate) struct EmbeddedTable {
    pub pdb_guid: &'static str,
    pub build_id: &'static str,
    pub obp_root_rva: u32,
    pub obp_info_mask_rva: u32,
}

pub(crate) static EMBEDDED_TABLES: &[&[EmbeddedTable]] = &[
    part_00::TABLE,
    part_01::TABLE,
    part_02::TABLE,
    part_03::TABLE,
    part_04::TABLE,
    part_05::TABLE,
    part_06::TABLE,
    part_07::TABLE,
    part_08::TABLE,
    part_09::TABLE,
    part_10::TABLE,
    part_11::TABLE,
    part_12::TABLE,
    part_13::TABLE,
];
