//! Import state management for incremental imports.
//!
//! Tracks import progress and supports pause/resume functionality.

use serde::{Deserialize, Serialize};

/// Typed error for import state persistence operations.
#[derive(Debug, thiserror::Error)]
pub enum ImportStateError {
    #[error("I/O error: {0}")]
    Io(#[from] std::io::Error),
    #[error("serialization error: {0}")]
    Serde(#[from] serde_json::Error),
}

impl transport::ServiceErrorCategory for ImportStateError {
    fn category(&self) -> transport::ErrorCategory {
        match self {
            Self::Io(_) => transport::ErrorCategory::Io,
            Self::Serde(_) => transport::ErrorCategory::Parser,
        }
    }
}

/// Import phase
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum ImportPhase {
    /// Classifying data source type
    Classifying,
    /// Enumerating filesystem
    Enumerating,
    /// Running post-import pipeline
    PostProcessing,
    /// Import completed
    Completed,
    /// Import failed
    Failed,
    /// Import paused by user
    Paused,
}

/// Import state for tracking progress
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ImportState {
    /// Job ID
    pub job_id: String,
    /// Data source ID
    pub data_source_id: String,
    /// Current phase
    pub phase: ImportPhase,
    /// Number of files processed
    pub processed_files: u64,
    /// Total number of files (estimated)
    pub total_files: u64,
    /// Last processed file path (for resume)
    pub last_processed_path: Option<String>,
    /// Errors encountered
    pub errors: Vec<ImportError>,
    /// Start time (ISO 8601)
    pub started_at: String,
    /// Last update time (ISO 8601)
    pub updated_at: String,
}

/// Import error record
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ImportError {
    /// Error message
    pub message: String,
    /// File path that caused the error
    pub file_path: Option<String>,
    /// Error timestamp
    pub timestamp: String,
}

/// Import plan generated by pre-check
#[derive(Debug, Clone)]
pub struct ImportPlan {
    /// Recommended strategy
    pub strategy: ImportStrategy,
    /// Estimated import time in seconds
    pub estimated_time_secs: u64,
    /// Estimated memory usage in bytes
    pub estimated_memory_bytes: u64,
    /// Total files to process
    pub total_files: u64,
    /// Total size in bytes
    pub total_size: u64,
}

/// Import strategy
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ImportStrategy {
    /// Sequential processing (small imports)
    Sequential,
    /// Parallel processing (medium imports)
    Parallel { workers: usize },
    /// Streaming processing (large files)
    Streaming,
    /// Adaptive (auto-select based on size)
    Adaptive,
}

impl ImportState {
    /// Create a new import state
    pub fn new(job_id: String, data_source_id: String) -> Self {
        let now = chrono::Utc::now().to_rfc3339();
        Self {
            job_id,
            data_source_id,
            phase: ImportPhase::Classifying,
            processed_files: 0,
            total_files: 0,
            last_processed_path: None,
            errors: Vec::new(),
            started_at: now.clone(),
            updated_at: now,
        }
    }

    /// Update progress
    pub fn update_progress(&mut self, processed: u64, total: u64) {
        self.processed_files = processed;
        self.total_files = total;
        self.updated_at = chrono::Utc::now().to_rfc3339();
    }

    /// Update phase
    pub fn set_phase(&mut self, phase: ImportPhase) {
        self.phase = phase;
        self.updated_at = chrono::Utc::now().to_rfc3339();
    }

    /// Add an error
    pub fn add_error(&mut self, message: String, file_path: Option<String>) {
        self.errors.push(ImportError {
            message,
            file_path,
            timestamp: chrono::Utc::now().to_rfc3339(),
        });
        self.updated_at = chrono::Utc::now().to_rfc3339();
    }

    /// Update last processed path
    pub fn set_last_processed(&mut self, path: String) {
        self.last_processed_path = Some(path);
        self.updated_at = chrono::Utc::now().to_rfc3339();
    }

    /// Check if import can be resumed
    pub fn can_resume(&self) -> bool {
        matches!(self.phase, ImportPhase::Paused | ImportPhase::Failed)
    }

    /// Get progress percentage (0-100)
    pub fn progress_percent(&self) -> u32 {
        if self.total_files == 0 {
            return 0;
        }
        ((self.processed_files as f64 / self.total_files as f64) * 100.0) as u32
    }

    /// Save state to file
    pub fn save(&self, path: &Path) -> Result<(), ImportStateError> {
        let json = serde_json::to_string_pretty(self)?;
        std::fs::write(path, json)?;
        Ok(())
    }

    /// Load state from file
    pub fn load(path: &Path) -> Result<Self, ImportStateError> {
        let json = std::fs::read_to_string(path)?;
        Ok(serde_json::from_str(&json)?)
    }
}

impl ImportPlan {
    /// Create a new import plan
    pub fn new(strategy: ImportStrategy, total_files: u64, total_size: u64) -> Self {
        let estimated_time_secs = Self::estimate_time(total_files, total_size, &strategy);
        let estimated_memory_bytes = Self::estimate_memory(&strategy, total_size);

        Self {
            strategy,
            estimated_time_secs,
            estimated_memory_bytes,
            total_files,
            total_size,
        }
    }

    /// Estimate import time in seconds
    fn estimate_time(files: u64, size: u64, strategy: &ImportStrategy) -> u64 {
        // Base: ~1000 files/second for sequential
        let base_rate = match strategy {
            ImportStrategy::Sequential => 1000.0,
            ImportStrategy::Parallel { workers } => 1000.0 * (*workers as f64),
            ImportStrategy::Streaming => 800.0,
            ImportStrategy::Adaptive => 1000.0,
        };

        let file_time = files as f64 / base_rate;
        // Size factor: ~100MB/second
        let size_time = size as f64 / (100.0 * 1024.0 * 1024.0);

        (file_time.max(size_time).ceil() as u64).max(1)
    }

    /// Estimate memory usage
    fn estimate_memory(strategy: &ImportStrategy, _size: u64) -> u64 {
        match strategy {
            ImportStrategy::Sequential => 100 * 1024 * 1024, // 100MB
            ImportStrategy::Parallel { workers } => 100 * 1024 * 1024 * (*workers as u64),
            ImportStrategy::Streaming => 64 * 1024 * 1024, // 64MB
            ImportStrategy::Adaptive => 200 * 1024 * 1024, // 200MB
        }
    }
}

use std::path::Path;

#[cfg(test)]
#[path = "../tests/unit/import_state.rs"]
mod tests;
