import { Button } from '@/app/components/ui/button';
import type { TFunction } from 'i18next';
import { createElement, type ReactNode } from 'react';
import { mcpIcons } from '../mcp-icons';
import type { McpServer } from '@/stores/mcp-types';
import type { ComponentType } from 'react';
import type { McpServerItemData } from './McpServerItemView';
type Row = McpServerItemData & { component: ComponentType<any> };
export function McpSectionView({ t, expanded, loading, onToggle, onAdd, servers, selectedServerId, onSelect, onConnect, onDisconnect, onRemove, hostToolList, resourceList, toolList, error, dialog }: { t: TFunction; expanded: boolean; loading: boolean; onToggle: () => void; onAdd: () => void; servers: Row[]; selectedServerId: string | null; onSelect: (id: string) => void; onConnect: (id: string) => void; onDisconnect: (id: string) => void; onRemove: (id: string) => void; hostToolList?: ReactNode; resourceList?: ReactNode; toolList?: ReactNode; error: string | null; dialog?: ReactNode }) { const { Bot, ChevronDown, ChevronRight, Plus } = mcpIcons; return <section><Button type="button" variant="forensicsGhost" size="inline" aria-expanded={expanded} onClick={onToggle} className="mb-3 flex h-auto w-full justify-start gap-2 px-0 text-left"><Bot size={14} /><span>{t('settings.sections.mcp.title')}</span>{expanded ? <ChevronDown size={14} /> : <ChevronRight size={14} />}{loading ? <span className="text-[10px]">{t('settings.sections.mcp.loading')}</span> : null}</Button>{expanded ? <div className="space-y-4">{hostToolList}<div className="bg-forensics-input-bg border border-forensics-border p-3"><div className="text-[11px] mb-2">{t('settings.sections.mcp.connectionTitle')}</div>{servers.length === 0 ? <div className="text-[11px] py-2">{t('settings.sections.mcp.noServers')}</div> : servers.map((server) => <div key={server.id}>{createElement(server.component, { server, isSelected: server.id === selectedServerId, onConnect: () => onConnect(server.id), onDisconnect: () => onDisconnect(server.id), onRemove: () => onRemove(server.id), onSelect: () => onSelect(server.id) })}</div>)}<Button type="button" variant="forensicsGhost" size="xs" onClick={onAdd}><Plus size={12} />{t('settings.sections.mcp.addServer')}</Button></div>{selectedServerId ? <div className="grid grid-cols-1 gap-4 xl:grid-cols-2">{resourceList}{toolList}</div> : null}<div className="text-[11px]">{t('settings.sections.mcp.connectionStatus', { count: servers.filter((server) => server.connected).length })}</div>{error ? <div className="p-3 text-[12px] bg-forensics-error-bg text-forensics-error-text">{error}</div> : null}</div> : null}{dialog}</section>; }
