[package]
name = "gql"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
domain.workspace = true
transport.workspace = true
persistence-sqlite.workspace = true
rusqlite.workspace = true
